//'alert('test')
const schools =
[
  {
    "School ID": 242,
    "School Name": "Ser Bany Yas",
    "School Name Arabic": "صير بني ياس",
    "Region": "Abu Dhabi",
    "Address": "MBZ",
    "GPS_LATITUDE": 24.32991071,
    "GPS_LONGITUDE": 54.53173914,
    "Gender": "M",
    "Alef IT Support Specialist": "Srour Khaled Mustafa Irshaid",
    "Alef IT Support Specialist Contact Number": "0549954818",
    "Alef IT Support Specialist Email": "srour.irshaid@alef.ae",
    "Alef IT Support Team Lead": "Yaman M.Alomari",
    "Alef IT Support Team Lead Contact Number": 509871697,
    "Alef IT Support Team Lead Email": "yaman@alef.ae"
  },
  {
    "School ID": 248,
    "School Name": "AL TAWEELAH",
    "School Name Arabic": "الطويلة",
    "Region": "Abu Dhabi",
    "Address": "AL SAMHA",
    "GPS_LATITUDE": 24.67030964,
    "GPS_LONGITUDE": 54.75594389,
    "Gender": "F",
    "Alef IT Support Specialist": "Nada Abdelrahim Abdallah Mohamed",
    "Alef IT Support Specialist Contact Number": "0562474821",
    "Alef IT Support Specialist Email": "nada.abdallah@alef.ae",
    "Alef IT Support Team Lead": "Sahar Gawad N Salah",
    "Alef IT Support Team Lead Contact Number": 509865704,
    "Alef IT Support Team Lead Email": "sahar@alef.ae"
  },
  {
    "School ID": 253,
    "School Name": "Al Ghazali",
    "School Name Arabic": "الغزالي",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI ISLAND",
    "GPS_LATITUDE": 24.4575,
    "GPS_LONGITUDE": 54.3401,
    "Gender": "M",
    "Alef IT Support Specialist": "Abdul hakim",
    "Alef IT Support Specialist Contact Number": "0545815574",
    "Alef IT Support Specialist Email": "abdul.hakkim@alef.ae",
    "Alef IT Support Team Lead": "Yaman M.Alomari",
    "Alef IT Support Team Lead Contact Number": 509871697,
    "Alef IT Support Team Lead Email": "yaman@alef.ae"
  },
  {
    "School ID": 256,
    "School Name": "AIN JALOOT",
    "School Name Arabic": "عين جالوت",
    "Region": "Abu Dhabi",
    "Address": "AL BAHYA",
    "GPS_LATITUDE": 24.51972511,
    "GPS_LONGITUDE": 54.66269643,
    "Gender": "F",
    "Alef IT Support Specialist": "Aseel Mohammad Nasoh Khoder",
    "Alef IT Support Specialist Contact Number": "0549944848",
    "Alef IT Support Specialist Email": "aseel.khoder@alef.ae",
    "Alef IT Support Team Lead": "Sahar Gawad N Salah",
    "Alef IT Support Team Lead Contact Number": 509865704,
    "Alef IT Support Team Lead Email": "sahar@alef.ae"
  },
  {
    "School ID": 273,
    "School Name": "Zayed Al Thani",
    "School Name Arabic": "زايد الثاني",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI ISLAND",
    "GPS_LATITUDE": 24.459594457,
    "GPS_LONGITUDE": 54.382958903,
    "Gender": "M",
    "Alef IT Support Specialist": "Abdallah Salah Khamees",
    "Alef IT Support Specialist Contact Number": "0569901232",
    "Alef IT Support Specialist Email": "abdallah@alef.ae",
    "Alef IT Support Team Lead": "Yaman M.Alomari",
    "Alef IT Support Team Lead Contact Number": 509871697,
    "Alef IT Support Team Lead Email": "yaman@alef.ae"
  },
  {
    "School ID": 283,
    "School Name": "Khalifah Bin Zayed (AD)",
    "School Name Arabic": "خليفة بن زايد",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI ISLAND",
    "GPS_LATITUDE": 24.4295,
    "GPS_LONGITUDE": 54.4075,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohammed Tharwar Ahmed Mohamed Elmesalamy",
    "Alef IT Support Specialist Contact Number": "0505196780",
    "Alef IT Support Specialist Email": "mohammed.elmesalamy@alef.ae",
    "Alef IT Support Team Lead": "Yaman M.Alomari",
    "Alef IT Support Team Lead Contact Number": 509871697,
    "Alef IT Support Team Lead Email": "yaman@alef.ae"
  },
  {
    "School ID": 294,
    "School Name": "Al Sameeh",
    "School Name Arabic": "السميح",
    "Region": "Abu Dhabi",
    "Address": "AL RAHBA",
    "GPS_LATITUDE": 24.6417,
    "GPS_LONGITUDE": 54.7303,
    "Gender": "M",
    "Alef IT Support Specialist": "MOHAMMED ABDULRAHMAN DARSI ABDULRAHMAN",
    "Alef IT Support Specialist Contact Number": "0569932352",
    "Alef IT Support Specialist Email": "muhammed.abdulrahman@alef.ae",
    "Alef IT Support Team Lead": "Mohammad Riyad Ahmad Salaimeh",
    "Alef IT Support Team Lead Contact Number": 565024500,
    "Alef IT Support Team Lead Email": "Mohammed.Salaimeh@alef.ae"
  },
  {
    "School ID": 296,
    "School Name": "Salamah Bint Buti",
    "School Name Arabic": "سلامة بنت بطي",
    "Region": "Abu Dhabi",
    "Address": "BANIYAS",
    "GPS_LATITUDE": 24.29840708,
    "GPS_LONGITUDE": 54.63429928,
    "Gender": "F",
    "Alef IT Support Specialist": "Rofaida Babikir Abdalraheem Babiker",
    "Alef IT Support Specialist Contact Number": "0566885896",
    "Alef IT Support Specialist Email": "rofaida.babiker@alef.ae",
    "Alef IT Support Team Lead": "Nusaybah Mahmoud Nail Alzghoul",
    "Alef IT Support Team Lead Contact Number": 569940198,
    "Alef IT Support Team Lead Email": "Nusaybah.Alzghoul@alef.ae"
  },
  {
    "School ID": 298,
    "School Name": "Al Qarm",
    "School Name Arabic": "القرم",
    "Region": "Abu Dhabi",
    "Address": "MOHAMED BIN ZAYED CITY",
    "GPS_LATITUDE": 24.37590379,
    "GPS_LONGITUDE": 54.53703898,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohammad Abu-Hashish",
    "Alef IT Support Specialist Contact Number": "0569902784",
    "Alef IT Support Specialist Email": "mohammad.abuhashish@alef.ae",
    "Alef IT Support Team Lead": "Yaman M.Alomari",
    "Alef IT Support Team Lead Contact Number": 509871697,
    "Alef IT Support Team Lead Email": "yaman@alef.ae"
  },
  {
    "School ID": 303,
    "School Name": "Al Ajbaan",
    "School Name Arabic": "العجبان",
    "Region": "Abu Dhabi",
    "Address": "AL SHAHAMA",
    "GPS_LATITUDE": 24.5259,
    "GPS_LONGITUDE": 54.6785,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohammad Salah",
    "Alef IT Support Specialist Contact Number": "0569902785",
    "Alef IT Support Specialist Email": "mohammadsalah@alef.ae",
    "Alef IT Support Team Lead": "Mohammad Riyad Ahmad Salaimeh",
    "Alef IT Support Team Lead Contact Number": 565024500,
    "Alef IT Support Team Lead Email": "Mohammed.Salaimeh@alef.ae"
  },
  {
    "School ID": 320,
    "School Name": "IBN SINA",
    "School Name Arabic": "ابن سينا للتعليم الأساسي",
    "Region": "Abu Dhabi",
    "Address": "AL SHAHAMA",
    "GPS_LATITUDE": 24.5213,
    "GPS_LONGITUDE": 54.6887,
    "Gender": "M",
    "Alef IT Support Specialist": "Khaled Taher Salem Barbar",
    "Alef IT Support Specialist Contact Number": "0505175296",
    "Alef IT Support Specialist Email": "Khaled.Barber@alef.ae",
    "Alef IT Support Team Lead": "Mohammad Riyad Ahmad Salaimeh",
    "Alef IT Support Team Lead Contact Number": 565024500,
    "Alef IT Support Team Lead Email": "Mohammed.Salaimeh@alef.ae"
  },
  {
    "School ID": 325,
    "School Name": "Al Mawaheb",
    "School Name Arabic": "المواهب",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI ISLAND",
    "GPS_LATITUDE": 24.4625,
    "GPS_LONGITUDE": 54.3481,
    "Gender": "F",
    "Alef IT Support Specialist": "Marry Hanna Nassif Abuelssad",
    "Alef IT Support Specialist Contact Number": "0505205647",
    "Alef IT Support Specialist Email": "Marry.Hanna@alef.ae",
    "Alef IT Support Team Lead": "Samah Mukhtar",
    "Alef IT Support Team Lead Contact Number": 564008391,
    "Alef IT Support Team Lead Email": "samah.mukhtar@alef.ae"
  },
  {
    "School ID": 335,
    "School Name": "Al Reef",
    "School Name Arabic": "الريف",
    "Region": "Abu Dhabi",
    "Address": "AL SHAHAMA",
    "GPS_LATITUDE": 24.54121672,
    "GPS_LONGITUDE": 54.68031785,
    "Gender": "F",
    "Alef IT Support Specialist": "Siham Lakhlifi",
    "Alef IT Support Specialist Contact Number": "0505193718",
    "Alef IT Support Specialist Email": "siham.lakhlifi@alef.ae",
    "Alef IT Support Team Lead": "Sahar Gawad N Salah",
    "Alef IT Support Team Lead Contact Number": 509865704,
    "Alef IT Support Team Lead Email": "sahar@alef.ae"
  },
  {
    "School ID": 339,
    "School Name": "Al Tafawwoq",
    "School Name Arabic": "التفوق",
    "Region": "Abu Dhabi",
    "Address": "AL SHAMKHA",
    "GPS_LATITUDE": 24.3973,
    "GPS_LONGITUDE": 54.7333,
    "Gender": "M",
    "Alef IT Support Specialist": "Ahmad Mahmoud Orabi Jarrar",
    "Alef IT Support Specialist Contact Number": "0505176159",
    "Alef IT Support Specialist Email": "Ahmad.Jarrar@alef.ae",
    "Alef IT Support Team Lead": "Mohammad Riyad Ahmad Salaimeh",
    "Alef IT Support Team Lead Contact Number": 565024500,
    "Alef IT Support Team Lead Email": "Mohammed.Salaimeh@alef.ae"
  },
  {
    "School ID": 351,
    "School Name": "AL BAHEYAH",
    "School Name Arabic": "الباهية",
    "Region": "Abu Dhabi",
    "Address": "AL SHAHAMA",
    "GPS_LATITUDE": 24.5493,
    "GPS_LONGITUDE": 54.6811,
    "Gender": "M",
    "Alef IT Support Specialist": "Khaled Taher Salem Barbar",
    "Alef IT Support Specialist Contact Number": "0505175296",
    "Alef IT Support Specialist Email": "Khaled.Barber@alef.ae",
    "Alef IT Support Team Lead": "Mohammad Riyad Ahmad Salaimeh",
    "Alef IT Support Team Lead Contact Number": 565024500,
    "Alef IT Support Team Lead Email": "Mohammed.Salaimeh@alef.ae"
  },
  {
    "School ID": 362,
    "School Name": "Al Moatasem",
    "School Name Arabic": "المعتصم",
    "Region": "Abu Dhabi",
    "Address": "BANIYAS",
    "GPS_LATITUDE": 24.29259267,
    "GPS_LONGITUDE": 54.65559981,
    "Gender": "M",
    "Alef IT Support Specialist": "ODAY MOH'D KHALIL AL KAFAWIN",
    "Alef IT Support Specialist Contact Number": "0569940245",
    "Alef IT Support Specialist Email": "oday.kafawin@alef.ae",
    "Alef IT Support Team Lead": "Iyad Hasan Salman",
    "Alef IT Support Team Lead Contact Number": 564008645,
    "Alef IT Support Team Lead Email": "iyad@alef.ae"
  },
  {
    "School ID": 369,
    "School Name": "Al Suqoor",
    "School Name Arabic": "الصقور",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI ISLAND",
    "GPS_LATITUDE": 24.4793,
    "GPS_LONGITUDE": 54.3765,
    "Gender": "M",
    "Alef IT Support Specialist": "Sa'ed Abdullah Al-Husan",
    "Alef IT Support Specialist Contact Number": "0509865066",
    "Alef IT Support Specialist Email": "saed.abdulla@alef.ae",
    "Alef IT Support Team Lead": "Yaman M.Alomari",
    "Alef IT Support Team Lead Contact Number": 509871697,
    "Alef IT Support Team Lead Email": "yaman@alef.ae"
  },
  {
    "School ID": 374,
    "School Name": "Al Aasimah",
    "School Name Arabic": "العاصمة",
    "Region": "Abu Dhabi",
    "Address": "AL SHAMKHA",
    "GPS_LATITUDE": 24.37653256,
    "GPS_LONGITUDE": 54.71247245,
    "Gender": "M",
    "Alef IT Support Specialist": "Ahmad Sulieman Salem Aldakheel",
    "Alef IT Support Specialist Contact Number": "0569943186",
    "Alef IT Support Specialist Email": "Ahmad.Aldakheel@alef.ae",
    "Alef IT Support Team Lead": "Mohammad Riyad Ahmad Salaimeh",
    "Alef IT Support Team Lead Contact Number": 565024500,
    "Alef IT Support Team Lead Email": "Mohammed.Salaimeh@alef.ae"
  },
  {
    "School ID": 387,
    "School Name": "Al Ittihad",
    "School Name Arabic": "الاتحاد",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI ISLAND",
    "GPS_LATITUDE": 24.46157151,
    "GPS_LONGITUDE": 54.34321421,
    "Gender": "M",
    "Alef IT Support Specialist": "Moussa Jamil Samman",
    "Alef IT Support Specialist Contact Number": "0569924730",
    "Alef IT Support Specialist Email": "moussa.samman@alef.ae",
    "Alef IT Support Team Lead": "Yaman M.Alomari",
    "Alef IT Support Team Lead Contact Number": 509871697,
    "Alef IT Support Team Lead Email": "yaman@alef.ae"
  },
  {
    "School ID": 391,
    "School Name": "Maryam Bint Omran",
    "School Name Arabic": "مريم بنت عمران",
    "Region": "Abu Dhabi",
    "Address": "BANIYAS",
    "GPS_LATITUDE": 24.28580086,
    "GPS_LONGITUDE": 54.64899866,
    "Gender": "F",
    "Alef IT Support Specialist": "Hadeel Khaled Moh'd Hayajneh",
    "Alef IT Support Specialist Contact Number": "0566893109",
    "Alef IT Support Specialist Email": "hadeel.hayajneh@alef.ae",
    "Alef IT Support Team Lead": "Nusaybah Mahmoud Nail Alzghoul",
    "Alef IT Support Team Lead Contact Number": 569940198,
    "Alef IT Support Team Lead Email": "Nusaybah.Alzghoul@alef.ae"
  },
  {
    "School ID": 392,
    "School Name": "AL RAHBA",
    "School Name Arabic": "الرحبة",
    "Region": "Abu Dhabi",
    "Address": "AL RAHBA",
    "GPS_LATITUDE": 24.5951,
    "GPS_LONGITUDE": 54.7007,
    "Gender": "F",
    "Alef IT Support Specialist": "Ala' Hasan Ahmad Al Sayed",
    "Alef IT Support Specialist Contact Number": "0562474679",
    "Alef IT Support Specialist Email": "ala.alsayed@alef.ae",
    "Alef IT Support Team Lead": "Sahar Gawad N Salah",
    "Alef IT Support Team Lead Contact Number": 509865704,
    "Alef IT Support Team Lead Email": "sahar@alef.ae"
  },
  {
    "School ID": 393,
    "School Name": "Moza Bint Butti",
    "School Name Arabic": "موزة بنت بطي",
    "Region": "Abu Dhabi",
    "Address": "AL RAHBA",
    "GPS_LATITUDE": 24.5569,
    "GPS_LONGITUDE": 54.6771,
    "Gender": "F",
    "Alef IT Support Specialist": "Hajer Hashim",
    "Alef IT Support Specialist Contact Number": "0509871652",
    "Alef IT Support Specialist Email": "Hajer.hashim@alef.ae",
    "Alef IT Support Team Lead": "Sahar Gawad N Salah",
    "Alef IT Support Team Lead Contact Number": 509865704,
    "Alef IT Support Team Lead Email": "sahar@alef.ae"
  },
  {
    "School ID": 397,
    "School Name": "Obadah Bin Al Samet",
    "School Name Arabic": "عبادة بن الصامت",
    "Region": "Abu Dhabi",
    "Address": "AL KHATIM",
    "GPS_LATITUDE": 24.1823,
    "GPS_LONGITUDE": 55.0051,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohammad Waled Mohammad Qeisi",
    "Alef IT Support Specialist Contact Number": "0505196153",
    "Alef IT Support Specialist Email": "Mohammad.Qeisi@alef.ae",
    "Alef IT Support Team Lead": "Iyad Hasan Salman",
    "Alef IT Support Team Lead Contact Number": 564008645,
    "Alef IT Support Team Lead Email": "iyad@alef.ae"
  },
  {
    "School ID": 408,
    "School Name": "Hamza Bin Abdul Muttalib",
    "School Name Arabic": "حمزة بن عبدالمطلب",
    "Region": "Abu Dhabi",
    "Address": "BANIYAS",
    "GPS_LATITUDE": 24.29337483,
    "GPS_LONGITUDE": 54.64077138,
    "Gender": "M",
    "Alef IT Support Specialist": "Moustafa Taha Moustafa Al-foudeh",
    "Alef IT Support Specialist Contact Number": "0569925405",
    "Alef IT Support Specialist Email": "Moustafa.Alfoudeh@alef.ae",
    "Alef IT Support Team Lead": "Iyad Hasan Salman",
    "Alef IT Support Team Lead Contact Number": 564008645,
    "Alef IT Support Team Lead Email": "iyad@alef.ae"
  },
  {
    "School ID": 417,
    "School Name": "Al Ruwad",
    "School Name Arabic": "الرواد",
    "Region": "Abu Dhabi",
    "Address": "AL NAHDA",
    "GPS_LATITUDE": 24.2400015,
    "GPS_LONGITUDE": 54.72484277,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohammed Bassam Mohammad Al Rashaidat",
    "Alef IT Support Specialist Contact Number": "0505198147",
    "Alef IT Support Specialist Email": "mohammad.alrashaidat@alef.ae",
    "Alef IT Support Team Lead": "Iyad Hasan Salman",
    "Alef IT Support Team Lead Contact Number": 564008645,
    "Alef IT Support Team Lead Email": "iyad@alef.ae"
  },
  {
    "School ID": 418,
    "School Name": "Darwish Bin Karam",
    "School Name Arabic": "درويش بن كرم",
    "Region": "Abu Dhabi",
    "Address": "AL MAQTA AREA",
    "GPS_LATITUDE": 24.4057,
    "GPS_LONGITUDE": 54.5035,
    "Gender": "M",
    "Alef IT Support Specialist": "Hashim Mohamed Ibrahim Ahmed",
    "Alef IT Support Specialist Contact Number": "0505184738",
    "Alef IT Support Specialist Email": "Hashim.Ibrahim@alef.ae",
    "Alef IT Support Team Lead": "Yaman M.Alomari",
    "Alef IT Support Team Lead Contact Number": 509871697,
    "Alef IT Support Team Lead Email": "yaman@alef.ae"
  },
  {
    "School ID": 424,
    "School Name": "Al Samha",
    "School Name Arabic": "السمحة",
    "Region": "Abu Dhabi",
    "Address": "AL SAMHA",
    "GPS_LATITUDE": 24.68184765,
    "GPS_LONGITUDE": 54.77696174,
    "Gender": "F",
    "Alef IT Support Specialist": "Amna Elawad Fadlalla Elhussein",
    "Alef IT Support Specialist Contact Number": "0505178454",
    "Alef IT Support Specialist Email": "amna.fadlalla@alef.ae",
    "Alef IT Support Team Lead": "Sahar Gawad N Salah",
    "Alef IT Support Team Lead Contact Number": 509865704,
    "Alef IT Support Team Lead Email": "sahar@alef.ae"
  },
  {
    "School ID": 428,
    "School Name": "Al Montaha",
    "School Name Arabic": "المنتهى",
    "Region": "Abu Dhabi",
    "Address": "MOHAMED BIN ZAYED CITY",
    "GPS_LATITUDE": 24.3187,
    "GPS_LONGITUDE": 54.5345,
    "Gender": "F",
    "Alef IT Support Specialist": "Sherin Mohamed Ahmed Murad Hafez",
    "Alef IT Support Specialist Contact Number": "0566894336",
    "Alef IT Support Specialist Email": "sherin.hafez@alef.ae",
    "Alef IT Support Team Lead": "Samah Mukhtar",
    "Alef IT Support Team Lead Contact Number": 564008391,
    "Alef IT Support Team Lead Email": "samah.mukhtar@alef.ae"
  },
  {
    "School ID": 448,
    "School Name": "Al Asalah",
    "School Name Arabic": "الأصالة",
    "Region": "Abu Dhabi",
    "Address": "AL SHAMKHA",
    "GPS_LATITUDE": 24.4065,
    "GPS_LONGITUDE": 54.7323,
    "Gender": "F",
    "Alef IT Support Specialist": "Mariam Alqubalsi",
    "Alef IT Support Specialist Contact Number": "0566894337",
    "Alef IT Support Specialist Email": "mariam.alqubaisi@alef.ae",
    "Alef IT Support Team Lead": "Sahar Gawad N Salah",
    "Alef IT Support Team Lead Contact Number": 509865704,
    "Alef IT Support Team Lead Email": "sahar@alef.ae"
  },
  {
    "School ID": 451,
    "School Name": "Aljazira Football Academy",
    "School Name Arabic": "أكاديمية الجزيرة لكرة القدم",
    "Region": "Abu Dhabi",
    "Address": "AL SHAWAMEKH",
    "GPS_LATITUDE": 24.38144659,
    "GPS_LONGITUDE": 54.6645645,
    "Gender": "M",
    "Alef IT Support Specialist": "Sadem Mhamdi",
    "Alef IT Support Specialist Contact Number": "0569941326",
    "Alef IT Support Specialist Email": "Sadem.Mhamdi@alef.ae",
    "Alef IT Support Team Lead": "Mohammad Riyad Ahmad Salaimeh",
    "Alef IT Support Team Lead Contact Number": 565024500,
    "Alef IT Support Team Lead Email": "Mohammed.Salaimeh@alef.ae"
  },
  {
    "School ID": 453,
    "School Name": "Sas Al Nakhl",
    "School Name Arabic": "ساس النخل",
    "Region": "Abu Dhabi",
    "Address": "KHALIFA CITY",
    "GPS_LATITUDE": 24.4171,
    "GPS_LONGITUDE": 54.5687,
    "Gender": "M",
    "Alef IT Support Specialist": "Zaid Emad Hussein Ibrahim",
    "Alef IT Support Specialist Contact Number": "0509865032",
    "Alef IT Support Specialist Email": "zaid.ibrahim@alef.ae",
    "Alef IT Support Team Lead": "Yaman M.Alomari",
    "Alef IT Support Team Lead Contact Number": 509871697,
    "Alef IT Support Team Lead Email": "yaman@alef.ae"
  },
  {
    "School ID": 454,
    "School Name": "Al Waleed Bin Abdul Malek",
    "School Name Arabic": "الوليد بن عبدالملك",
    "Region": "Abu Dhabi",
    "Address": "AL NAHDA",
    "GPS_LATITUDE": 24.26179186,
    "GPS_LONGITUDE": 54.70574771,
    "Gender": "M",
    "Alef IT Support Specialist": "Ahmad Alafyouni",
    "Alef IT Support Specialist Contact Number": "0562363433",
    "Alef IT Support Specialist Email": "ahmad.alafyouni@alef.ae",
    "Alef IT Support Team Lead": "Nusaybah Mahmoud Nail Alzghoul",
    "Alef IT Support Team Lead Contact Number": 569940198,
    "Alef IT Support Team Lead Email": "Nusaybah.Alzghoul@alef.ae"
  },
  {
    "School ID": 465,
    "School Name": "Omamah Bint Al Harith",
    "School Name Arabic": "امامه بنت الحارث",
    "Region": "Abu Dhabi",
    "Address": "AL NAHDA",
    "GPS_LATITUDE": 24.2671,
    "GPS_LONGITUDE": 54.6961,
    "Gender": "F",
    "Alef IT Support Specialist": "Bushra Jameel Saleh Qumool",
    "Alef IT Support Specialist Contact Number": "0505179516",
    "Alef IT Support Specialist Email": "bushra.alqumool@alef.ae",
    "Alef IT Support Team Lead": "Nusaybah Mahmoud Nail Alzghoul",
    "Alef IT Support Team Lead Contact Number": 569940198,
    "Alef IT Support Team Lead Email": "Nusaybah.Alzghoul@alef.ae"
  },
  {
    "School ID": 468,
    "School Name": "Al Taqaddom",
    "School Name Arabic": "التقدم",
    "Region": "Abu Dhabi",
    "Address": "AL SHAMKHA",
    "GPS_LATITUDE": 24.3919,
    "GPS_LONGITUDE": 54.7373,
    "Gender": "F",
    "Alef IT Support Specialist": "Azza Ghribi",
    "Alef IT Support Specialist Contact Number": "0505183470",
    "Alef IT Support Specialist Email": "azza.ghribi@alef.ae",
    "Alef IT Support Team Lead": "Nusaybah Mahmoud Nail Alzghoul",
    "Alef IT Support Team Lead Contact Number": 569940198,
    "Alef IT Support Team Lead Email": "Nusaybah.Alzghoul@alef.ae"
  },
  {
    "School ID": 471,
    "School Name": "Al Asayel",
    "School Name Arabic": "الاصايل",
    "Region": "Abu Dhabi",
    "Address": "KHALIFA CITY",
    "GPS_LATITUDE": 24.4133,
    "GPS_LONGITUDE": 54.5709,
    "Gender": "F",
    "Alef IT Support Specialist": "Sulafa Hassan Abdelaziz Ahmed",
    "Alef IT Support Specialist Contact Number": "0509869185",
    "Alef IT Support Specialist Email": "sulafa.hassan@alef.ae",
    "Alef IT Support Team Lead": "Samah Mukhtar",
    "Alef IT Support Team Lead Contact Number": 564008391,
    "Alef IT Support Team Lead Email": "samah.mukhtar@alef.ae"
  },
  {
    "School ID": 482,
    "School Name": "Al Erteqaa",
    "School Name Arabic": "الارتقاء",
    "Region": "Abu Dhabi",
    "Address": "AL SHAMKHA",
    "GPS_LATITUDE": 24.40464646,
    "GPS_LONGITUDE": 54.73266036,
    "Gender": "F",
    "Alef IT Support Specialist": "Marwa Bassam Adi",
    "Alef IT Support Specialist Contact Number": "0505207122",
    "Alef IT Support Specialist Email": "Marwa.Adi@alef.ae",
    "Alef IT Support Team Lead": "Sahar Gawad N Salah",
    "Alef IT Support Team Lead Contact Number": 509865704,
    "Alef IT Support Team Lead Email": "sahar@alef.ae"
  },
  {
    "School ID": 489,
    "School Name": "Al Maha",
    "School Name Arabic": "المها",
    "Region": "Abu Dhabi",
    "Address": "AL FALAH",
    "GPS_LATITUDE": 24.4223,
    "GPS_LONGITUDE": 54.7417,
    "Gender": "F",
    "Alef IT Support Specialist": "Racha Ali Haitham Masri",
    "Alef IT Support Specialist Contact Number": "0569941156",
    "Alef IT Support Specialist Email": "racha.masri@alef.ae",
    "Alef IT Support Team Lead": "Sahar Gawad N Salah",
    "Alef IT Support Team Lead Contact Number": 509865704,
    "Alef IT Support Team Lead Email": "sahar@alef.ae"
  },
  {
    "School ID": 490,
    "School Name": "Saad Bin Moaath",
    "School Name Arabic": "سعد بن معاذ",
    "Region": "Abu Dhabi",
    "Address": "AL BAHYA",
    "GPS_LATITUDE": 24.5259,
    "GPS_LONGITUDE": 54.6727,
    "Gender": "M",
    "Alef IT Support Specialist": "Ahmed Mohamed El Sabagh",
    "Alef IT Support Specialist Contact Number": "0564008432",
    "Alef IT Support Specialist Email": "ahmed@alef.ae",
    "Alef IT Support Team Lead": "Mohammad Riyad Ahmad Salaimeh",
    "Alef IT Support Team Lead Contact Number": 565024500,
    "Alef IT Support Team Lead Email": "Mohammed.Salaimeh@alef.ae"
  },
  {
    "School ID": 493,
    "School Name": "Al Ta'awun",
    "School Name Arabic": "التعاون",
    "Region": "Abu Dhabi",
    "Address": "AL SHAMKHA",
    "GPS_LATITUDE": 24.37579105,
    "GPS_LONGITUDE": 54.7136087,
    "Gender": "M",
    "Alef IT Support Specialist": "Ahmad Sultan Mustafa Khadir",
    "Alef IT Support Specialist Contact Number": "0566893149",
    "Alef IT Support Specialist Email": "Ahmad.Khadir@alef.ae",
    "Alef IT Support Team Lead": "Mohammad Riyad Ahmad Salaimeh",
    "Alef IT Support Team Lead Contact Number": 565024500,
    "Alef IT Support Team Lead Email": "Mohammed.Salaimeh@alef.ae"
  },
  {
    "School ID": 495,
    "School Name": "Abu Dhabi Secondary",
    "School Name Arabic": "أبوظبي الثانوية",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI ISLAND",
    "GPS_LATITUDE": 24.45998923,
    "GPS_LONGITUDE": 54.367732,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohamed Ismail Ahmed El-rasheed",
    "Alef IT Support Specialist Contact Number": "0566032691",
    "Alef IT Support Specialist Email": "mohamed.elrasheed@alef.ae",
    "Alef IT Support Team Lead": "Yaman M.Alomari",
    "Alef IT Support Team Lead Contact Number": 509871697,
    "Alef IT Support Team Lead Email": "yaman@alef.ae"
  },
  {
    "School ID": 497,
    "School Name": "HALIMA AL SAADIAH",
    "School Name Arabic": "حليمة السعدية",
    "Region": "Abu Dhabi",
    "Address": "AL SHAHAMA",
    "GPS_LATITUDE": 24.55000257,
    "GPS_LONGITUDE": 54.68827251,
    "Gender": "F",
    "Alef IT Support Specialist": "Iman Hamed Almamari",
    "Alef IT Support Specialist Contact Number": "0509871938",
    "Alef IT Support Specialist Email": "iman.hamed@alef.ae",
    "Alef IT Support Team Lead": "Sahar Gawad N Salah",
    "Alef IT Support Team Lead Contact Number": 509865704,
    "Alef IT Support Team Lead Email": "sahar@alef.ae"
  },
  {
    "School ID": 506,
    "School Name": "Al Wathba",
    "School Name Arabic": "الوثبة",
    "Region": "Abu Dhabi",
    "Address": "AL NAHDA",
    "GPS_LATITUDE": 24.2441,
    "GPS_LONGITUDE": 54.7095,
    "Gender": "F",
    "Alef IT Support Specialist": "Mary Nasser Louis Meawad",
    "Alef IT Support Specialist Contact Number": "0505194668",
    "Alef IT Support Specialist Email": "Mary.meawad@alef.ae",
    "Alef IT Support Team Lead": "Nusaybah Mahmoud Nail Alzghoul",
    "Alef IT Support Team Lead Contact Number": 569940198,
    "Alef IT Support Team Lead Email": "Nusaybah.Alzghoul@alef.ae"
  },
  {
    "School ID": 509,
    "School Name": "Al Zallaqa",
    "School Name Arabic": "الزلاقة",
    "Region": "Abu Dhabi",
    "Address": "BANIYAS",
    "GPS_LATITUDE": 24.2991,
    "GPS_LONGITUDE": 54.6461,
    "Gender": "F",
    "Alef IT Support Specialist": "Iman Mahmoud Saeed",
    "Alef IT Support Specialist Contact Number": "0569902955",
    "Alef IT Support Specialist Email": "imansaeed@alef.ae",
    "Alef IT Support Team Lead": "Nusaybah Mahmoud Nail Alzghoul",
    "Alef IT Support Team Lead Contact Number": 569940198,
    "Alef IT Support Team Lead Email": "Nusaybah.Alzghoul@alef.ae"
  },
  {
    "School ID": 522,
    "School Name": "Al Bawadi",
    "School Name Arabic": "البوادي",
    "Region": "Abu Dhabi",
    "Address": "BANIYAS",
    "GPS_LATITUDE": 24.31381065,
    "GPS_LONGITUDE": 54.6298109,
    "Gender": "M",
    "Alef IT Support Specialist": "Faras ELFatih ELDukhairi",
    "Alef IT Support Specialist Contact Number": "0509867366",
    "Alef IT Support Specialist Email": "faras@alef.ae",
    "Alef IT Support Team Lead": "Iyad Hasan Salman",
    "Alef IT Support Team Lead Contact Number": 564008645,
    "Alef IT Support Team Lead Email": "iyad@alef.ae"
  },
  {
    "School ID": 544,
    "School Name": "Al Falahiyya",
    "School Name Arabic": "الفلاحية",
    "Region": "Abu Dhabi",
    "Address": "AL SAMHA",
    "GPS_LATITUDE": 24.68141077,
    "GPS_LONGITUDE": 54.77313964,
    "Gender": "M",
    "Alef IT Support Specialist": "Karim Alaaeldin Hassan Aly Souliman",
    "Alef IT Support Specialist Contact Number": "0505182483",
    "Alef IT Support Specialist Email": "karim.souliman@alef.ae",
    "Alef IT Support Team Lead": "Mohammad Riyad Ahmad Salaimeh",
    "Alef IT Support Team Lead Contact Number": 565024500,
    "Alef IT Support Team Lead Email": "Mohammed.Salaimeh@alef.ae"
  },
  {
    "School ID": 548,
    "School Name": "Aishah Bint Abi Baker",
    "School Name Arabic": "عائشة بنت ابي بكر",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI ISLAND",
    "GPS_LATITUDE": 24.44159317,
    "GPS_LONGITUDE": 54.40393795,
    "Gender": "F",
    "Alef IT Support Specialist": "Ibtihal M. M. Aldam",
    "Alef IT Support Specialist Contact Number": "0505181193",
    "Alef IT Support Specialist Email": "ibtihal.aldam@alef.ae",
    "Alef IT Support Team Lead": "Samah Mukhtar",
    "Alef IT Support Team Lead Contact Number": 564008391,
    "Alef IT Support Team Lead Email": "samah.mukhtar@alef.ae"
  },
  {
    "School ID": 641,
    "School Name": "Al Reem",
    "School Name Arabic": "الريم",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI ISLAND",
    "GPS_LATITUDE": 24.4357,
    "GPS_LONGITUDE": 54.4325,
    "Gender": "F",
    "Alef IT Support Specialist": "NOOR MOHAMMAD ABU-DA'ABES",
    "Alef IT Support Specialist Contact Number": "0501070858",
    "Alef IT Support Specialist Email": "noor.abudaabes@alef.ae",
    "Alef IT Support Team Lead": "Samah Mukhtar",
    "Alef IT Support Team Lead Contact Number": 564008391,
    "Alef IT Support Team Lead Email": "samah.mukhtar@alef.ae"
  },
  {
    "School ID": 1076,
    "School Name": "Al Khatem",
    "School Name Arabic": "الختم",
    "Region": "Abu Dhabi",
    "Address": "AL KHATIM",
    "GPS_LATITUDE": 24.1821,
    "GPS_LONGITUDE": 54.9941,
    "Gender": "0",
    "Alef IT Support Specialist": "Mona Saed Abdalla",
    "Alef IT Support Specialist Contact Number": "0566894338",
    "Alef IT Support Specialist Email": "mona.Abdalla@alef.ae",
    "Alef IT Support Team Lead": "Nusaybah Mahmoud Nail Alzghoul",
    "Alef IT Support Team Lead Contact Number": 569940198,
    "Alef IT Support Team Lead Email": "Nusaybah.Alzghoul@alef.ae"
  },
  {
    "School ID": 1079,
    "School Name": "Khalifa City A",
    "School Name Arabic": "مدرسة مدينة خليفة أ",
    "Region": "Abu Dhabi",
    "Address": "KHALIFA CITY",
    "GPS_LATITUDE": 24.41150689,
    "GPS_LONGITUDE": 54.58812379,
    "Gender": "F",
    "Alef IT Support Specialist": "Wiam Waleed Ahmed Sa'aydeh",
    "Alef IT Support Specialist Contact Number": "0569943151",
    "Alef IT Support Specialist Email": "wiam.ahmed@alef.ae",
    "Alef IT Support Team Lead": "Samah Mukhtar",
    "Alef IT Support Team Lead Contact Number": 564008391,
    "Alef IT Support Team Lead Email": "samah.mukhtar@alef.ae"
  },
  {
    "School ID": 1382,
    "School Name": "Al Qemma",
    "School Name Arabic": "مدرسه القمة",
    "Region": "Abu Dhabi",
    "Address": "AL SHAMKHA",
    "GPS_LATITUDE": 24.3641,
    "GPS_LONGITUDE": 54.6927,
    "Gender": "0",
    "Alef IT Support Specialist": "Rawan Alabdeh",
    "Alef IT Support Specialist Contact Number": "0566893146",
    "Alef IT Support Specialist Email": "Rawan.Alabdeh@alef.ae",
    "Alef IT Support Team Lead": "Nusaybah Mahmoud Nail Alzghoul",
    "Alef IT Support Team Lead Contact Number": 569940198,
    "Alef IT Support Team Lead Email": "Nusaybah.Alzghoul@alef.ae"
  },
  {
    "School ID": 1383,
    "School Name": "Al Reyada",
    "School Name Arabic": "الريادة",
    "Region": "Abu Dhabi",
    "Address": "AL SHAMKHA",
    "GPS_LATITUDE": 24.3893,
    "GPS_LONGITUDE": 54.6897,
    "Gender": "F",
    "Alef IT Support Specialist": "Alroumaithaa Abdalkareem Seralkhatem",
    "Alef IT Support Specialist Contact Number": "0569905156",
    "Alef IT Support Specialist Email": "alroumaithaa@alef.ae",
    "Alef IT Support Team Lead": "Nusaybah Mahmoud Nail Alzghoul",
    "Alef IT Support Team Lead Contact Number": 569940198,
    "Alef IT Support Team Lead Email": "Nusaybah.Alzghoul@alef.ae"
  },
  {
    "School ID": 1384,
    "School Name": "Al Shawamekh",
    "School Name Arabic": "مدرسة الشوامخ",
    "Region": "Abu Dhabi",
    "Address": "AL SHAWAMEKH",
    "GPS_LATITUDE": 24.3293,
    "GPS_LONGITUDE": 54.6451,
    "Gender": "F",
    "Alef IT Support Specialist": "FARDOUS MOUSA MOHAMMAD JAFAR",
    "Alef IT Support Specialist Contact Number": "0549946040",
    "Alef IT Support Specialist Email": "fardous.jaffar@alef.ae",
    "Alef IT Support Team Lead": "Nusaybah Mahmoud Nail Alzghoul",
    "Alef IT Support Team Lead Contact Number": 569940198,
    "Alef IT Support Team Lead Email": "Nusaybah.Alzghoul@alef.ae"
  },
  {
    "School ID": 1387,
    "School Name": "Al Mutanabi",
    "School Name Arabic": "مدرسه المتنبي",
    "Region": "Abu Dhabi",
    "Address": "BANIYAS",
    "GPS_LATITUDE": 24.3053,
    "GPS_LONGITUDE": 54.6545,
    "Gender": "M",
    "Alef IT Support Specialist": "Abdallah Haj",
    "Alef IT Support Specialist Contact Number": "0509868913",
    "Alef IT Support Specialist Email": "abdalla@alef.ae",
    "Alef IT Support Team Lead": "Iyad Hasan Salman",
    "Alef IT Support Team Lead Contact Number": 564008645,
    "Alef IT Support Team Lead Email": "iyad@alef.ae"
  },
  {
    "School ID": 1396,
    "School Name": "Fatima Bint Mubarak",
    "School Name Arabic": "مدرسة فاطمة بنت مبارك",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI ISLAND",
    "GPS_LATITUDE": 24.48298923,
    "GPS_LONGITUDE": 54.38113901,
    "Gender": "F",
    "Alef IT Support Specialist": "Norhan Adel ElBagory",
    "Alef IT Support Specialist Contact Number": "0564008082",
    "Alef IT Support Specialist Email": "norhan@alef.ae",
    "Alef IT Support Team Lead": "Samah Mukhtar",
    "Alef IT Support Team Lead Contact Number": 564008391,
    "Alef IT Support Team Lead Email": "samah.mukhtar@alef.ae"
  },
  {
    "School ID": 1397,
    "School Name": "Abdul Jaleel Al Fahim",
    "School Name Arabic": "مدرسة عبدالجليل الفهيم",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI ISLAND",
    "GPS_LATITUDE": 24.4417,
    "GPS_LONGITUDE": 54.4361,
    "Gender": "M",
    "Alef IT Support Specialist": "Ahmad Al-Akhrass",
    "Alef IT Support Specialist Contact Number": "0569901072",
    "Alef IT Support Specialist Email": "ahmad.akhrass@alef.ae",
    "Alef IT Support Team Lead": "Yaman M.Alomari",
    "Alef IT Support Team Lead Contact Number": 509871697,
    "Alef IT Support Team Lead Email": "yaman@alef.ae"
  },
  {
    "School ID": 1546,
    "School Name": "Al Marwa",
    "School Name Arabic": "المروة ",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI GATE CITY",
    "GPS_LATITUDE": 24.39369631,
    "GPS_LONGITUDE": 54.50026406,
    "Gender": "F",
    "Alef IT Support Specialist": "Lamia I. Darweesh",
    "Alef IT Support Specialist Contact Number": "0569903309",
    "Alef IT Support Specialist Email": "lamia@alef.ae",
    "Alef IT Support Team Lead": "Samah Mukhtar",
    "Alef IT Support Team Lead Contact Number": 564008391,
    "Alef IT Support Team Lead Email": "samah.mukhtar@alef.ae"
  },
  {
    "School ID": 1547,
    "School Name": "Hunain",
    "School Name Arabic": "حنين ",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI GATE CITY",
    "GPS_LATITUDE": 24.3935,
    "GPS_LONGITUDE": 54.4969,
    "Gender": "F",
    "Alef IT Support Specialist": "Zena Mahd Mohd Saleh",
    "Alef IT Support Specialist Contact Number": "0566886386",
    "Alef IT Support Specialist Email": "Zena.Saleh@alef.ae",
    "Alef IT Support Team Lead": "Samah Mukhtar",
    "Alef IT Support Team Lead Contact Number": 564008391,
    "Alef IT Support Team Lead Email": "samah.mukhtar@alef.ae"
  },
  {
    "School ID": 1707,
    "School Name": "Al Sammaliya",
    "School Name Arabic": "السمالية",
    "Region": "Abu Dhabi",
    "Address": "AL SHAWAMEKH",
    "GPS_LATITUDE": 24.3267,
    "GPS_LONGITUDE": 54.6434,
    "Gender": "M",
    "Alef IT Support Specialist": "Maisam Jamal Kaddoura",
    "Alef IT Support Specialist Contact Number": "0505196014",
    "Alef IT Support Specialist Email": "maisam.kaddoura@alef.ae",
    "Alef IT Support Team Lead": "Iyad Hasan Salman",
    "Alef IT Support Team Lead Contact Number": 564008645,
    "Alef IT Support Team Lead Email": "iyad@alef.ae"
  },
  {
    "School ID": 1722,
    "School Name": "Um Al Arab",
    "School Name Arabic": "أم العرب",
    "Region": "Abu Dhabi",
    "Address": "AL FALAH",
    "GPS_LATITUDE": 24.458419,
    "GPS_LONGITUDE": 54.721841,
    "Gender": "F",
    "Alef IT Support Specialist": "Areej Musa Bilal Babaker + Hanane Benzamia",
    "Alef IT Support Specialist Contact Number": "0508731105 + ('0549947896)",
    "Alef IT Support Specialist Email": "areej.babaker@alef.ae + hanane.benzamia@alef.ae",
    "Alef IT Support Team Lead": "Sahar Gawad N Salah",
    "Alef IT Support Team Lead Contact Number": 509865704,
    "Alef IT Support Team Lead Email": "sahar@alef.ae"
  },
  {
    "School ID": 1724,
    "School Name": "Yas",
    "School Name Arabic": "ياس",
    "Region": "Abu Dhabi",
    "Address": "YAS ISLAND",
    "GPS_LATITUDE": 24.503964422,
    "GPS_LONGITUDE": 54.591597013,
    "Gender": "0",
    "Alef IT Support Specialist": "Nada Abdelwahab Mohamed Elhassan Osman",
    "Alef IT Support Specialist Contact Number": "0569938572",
    "Alef IT Support Specialist Email": "Nada.Osman@alef.ae",
    "Alef IT Support Team Lead": "Sahar Gawad N Salah",
    "Alef IT Support Team Lead Contact Number": 509865704,
    "Alef IT Support Team Lead Email": "sahar@alef.ae"
  },
  {
    "School ID": 1725,
    "School Name": "Jern Yafoor",
    "School Name Arabic": "جرن يافور",
    "Region": "Abu Dhabi",
    "Address": "BANIYAS",
    "GPS_LATITUDE": 24.299357,
    "GPS_LONGITUDE": 54.620865,
    "Gender": "M",
    "Alef IT Support Specialist": "Ahmed Mohamed Mohamed Shanab",
    "Alef IT Support Specialist Contact Number": "0505177685",
    "Alef IT Support Specialist Email": "ahmed.shanab@alef.ae",
    "Alef IT Support Team Lead": "Iyad Hasan Salman",
    "Alef IT Support Team Lead Contact Number": 564008645,
    "Alef IT Support Team Lead Email": "iyad@alef.ae"
  },
  {
    "School ID": 1742,
    "School Name": "Al Qudra",
    "School Name Arabic": "القدرة",
    "Region": "Abu Dhabi",
    "Address": "AL FALAH",
    "GPS_LATITUDE": 24.4259,
    "GPS_LONGITUDE": 54.7297,
    "Gender": "M",
    "Alef IT Support Specialist": "Ibrahim Mohamed Ahmed Ahmed Aboamer",
    "Alef IT Support Specialist Contact Number": "0505185727",
    "Alef IT Support Specialist Email": "Ibrahim.Aboamer@alef.ae",
    "Alef IT Support Team Lead": "Mohammad Riyad Ahmad Salaimeh",
    "Alef IT Support Team Lead Contact Number": 565024500,
    "Alef IT Support Team Lead Email": "Mohammed.Salaimeh@alef.ae"
  },
  {
    "School ID": 1822,
    "School Name": "Hamdan Bin Zayed (F)",
    "School Name Arabic": "حمدان بن زايد - إناث",
    "Region": "Abu Dhabi",
    "Address": "ABU DHABI ISLAND",
    "GPS_LATITUDE": 24.460452,
    "GPS_LONGITUDE": 54.358551,
    "Gender": "F",
    "Alef IT Support Specialist": "Rima Riyad Hussein Sondos",
    "Alef IT Support Specialist Contact Number": "0509869620",
    "Alef IT Support Specialist Email": "rima@alef.ae",
    "Alef IT Support Team Lead": "Samah Mukhtar",
    "Alef IT Support Team Lead Contact Number": 564008391,
    "Alef IT Support Team Lead Email": "samah.mukhtar@alef.ae"
  },
  {
    "School ID": 2018,
    "School Name": "Rooh Al Ittihad",
    "School Name Arabic": "روح الاتحاد",
    "Region": "Abu Dhabi",
    "Address": "AL FALAH",
    "GPS_LATITUDE": 24.45639,
    "GPS_LONGITUDE": 54.7378,
    "Gender": "M",
    "Alef IT Support Specialist": "Fuad Jamal Saleh Hasan (+ Ahmad Omran Al Afyouni)",
    "Alef IT Support Specialist Contact Number": "0505183285",
    "Alef IT Support Specialist Email": "Fuad.Hasan@alef.ae (+ Ahmad.alafyouni@alef.ae)",
    "Alef IT Support Team Lead": "Mohammad Riyad Ahmad Salaimeh",
    "Alef IT Support Team Lead Contact Number": 565024500,
    "Alef IT Support Team Lead Email": "Mohammed.Salaimeh@alef.ae"
  },
  {
    "School ID": 2019,
    "School Name": "Bani Yas City",
    "School Name Arabic": "مدينة بني ياس",
    "Region": "Abu Dhabi",
    "Address": "BANIYAS",
    "GPS_LATITUDE": 24.284805949,
    "GPS_LONGITUDE": 54.647649914,
    "Gender": "F",
    "Alef IT Support Specialist": "Baraah Raid Farhoud",
    "Alef IT Support Specialist Contact Number": "0505179185",
    "Alef IT Support Specialist Email": "Baraah.Farhoud@alef.ae",
    "Alef IT Support Team Lead": "Nusaybah Mahmoud Nail Alzghoul",
    "Alef IT Support Team Lead Contact Number": 569940198,
    "Alef IT Support Team Lead Email": "Nusaybah.Alzghoul@alef.ae"
  },
  {
    "School ID": 2021,
    "School Name": "Mleih",
    "School Name Arabic": "مدرسة مليح",
    "Region": "Abu Dhabi",
    "Address": "SHAKHBOUT CITY",
    "GPS_LATITUDE": 24.3639,
    "GPS_LONGITUDE": 54.6358,
    "Gender": "F",
    "Alef IT Support Specialist": "HODA MASK",
    "Alef IT Support Specialist Contact Number": "0549946033",
    "Alef IT Support Specialist Email": "hoda.mask@alef.ae",
    "Alef IT Support Team Lead": "Samah Mukhtar",
    "Alef IT Support Team Lead Contact Number": 564008391,
    "Alef IT Support Team Lead Email": "samah.mukhtar@alef.ae"
  },
  {
    "School ID": 2026,
    "School Name": "Al Nahda",
    "School Name Arabic": "النهضة",
    "Region": "Abu Dhabi",
    "Address": "BANIYAS",
    "GPS_LATITUDE": 24.284282,
    "GPS_LONGITUDE": 54.653274,
    "Gender": "M",
    "Alef IT Support Specialist": "Ahmed Rajai Harb",
    "Alef IT Support Specialist Contact Number": "0566892879",
    "Alef IT Support Specialist Email": "ahmad.harb@alef.ae",
    "Alef IT Support Team Lead": "Iyad Hasan Salman",
    "Alef IT Support Team Lead Contact Number": 564008645,
    "Alef IT Support Team Lead Email": "iyad@alef.ae"
  },
  {
    "School ID": 2027,
    "School Name": "Hamdan Bin Zayed (M)",
    "School Name Arabic": "حمدان بن زايد - ذكور",
    "Region": "Abu Dhabi",
    "Address": "Al Mushrif",
    "GPS_LATITUDE": 24.4313,
    "GPS_LONGITUDE": 54.3957,
    "Gender": "M",
    "Alef IT Support Specialist": "Kareem Ramadan Hossney Mobarak",
    "Alef IT Support Specialist Contact Number": "0508731107",
    "Alef IT Support Specialist Email": "kareem.mobarak@alef.ae",
    "Alef IT Support Team Lead": "Yaman M.Alomari",
    "Alef IT Support Team Lead Contact Number": 509871697,
    "Alef IT Support Team Lead Email": "yaman@alef.ae"
  },
  {
    "School ID": 228,
    "School Name": "Khalifah Bin Zayed (AA)",
    "School Name Arabic": "خليفة بن زايد",
    "Region": "Al Ain",
    "Address": "AL JIMI",
    "GPS_LATITUDE": 24.26559292,
    "GPS_LONGITUDE": 55.73209988,
    "Gender": "M",
    "Alef IT Support Specialist": "Osman ElDaw Yousif Mohammed",
    "Alef IT Support Specialist Contact Number": "0569940581",
    "Alef IT Support Specialist Email": "osman.mohammed@alef.ae",
    "Alef IT Support Team Lead": "Ahmed Fathi Sayed",
    "Alef IT Support Team Lead Contact Number": 509869037,
    "Alef IT Support Team Lead Email": "ahmed.fathi@alef.ae"
  },
  {
    "School ID": 232,
    "School Name": "Ramah",
    "School Name Arabic": "رماح للتعليم",
    "Region": "Al Ain",
    "Address": "REMAH",
    "GPS_LATITUDE": 24.2063283,
    "GPS_LONGITUDE": 55.33904991,
    "Gender": "M",
    "Alef IT Support Specialist": "Mahamat Nour Abdallah Abdallah",
    "Alef IT Support Specialist Contact Number": "0505172731",
    "Alef IT Support Specialist Email": "mahamat.abdallah@alef.ae",
    "Alef IT Support Team Lead": "Esam Abu Yousif",
    "Alef IT Support Team Lead Contact Number": 565374399,
    "Alef IT Support Team Lead Email": "esam.abuyousif@alef.ae"
  },
  {
    "School ID": 234,
    "School Name": "Al Ma'ali",
    "School Name Arabic": "المعالي",
    "Region": "Al Ain",
    "Address": "FALAJ HAZZA",
    "GPS_LATITUDE": 24.1884072,
    "GPS_LONGITUDE": 55.73948954,
    "Gender": "F",
    "Alef IT Support Specialist": "Hazar Osama Hamza",
    "Alef IT Support Specialist Contact Number": "0569901387",
    "Alef IT Support Specialist Email": "hazar@alef.ae",
    "Alef IT Support Team Lead": "Samah Ali Ahmad",
    "Alef IT Support Team Lead Contact Number": 564018945,
    "Alef IT Support Team Lead Email": "samah.ali@alef.ae"
  },
  {
    "School ID": 239,
    "School Name": "Al Sadarah",
    "School Name Arabic": "الصدارة",
    "Region": "Al Ain",
    "Address": "AL KHABISI",
    "GPS_LATITUDE": 24.2235,
    "GPS_LONGITUDE": 55.6899,
    "Gender": "M",
    "Alef IT Support Specialist": "Ammar Sbahi",
    "Alef IT Support Specialist Contact Number": "0565015944",
    "Alef IT Support Specialist Email": "ammar.sbahi@alef.ae",
    "Alef IT Support Team Lead": "Esam Abu Yousif",
    "Alef IT Support Team Lead Contact Number": 565374399,
    "Alef IT Support Team Lead Email": "esam.abuyousif@alef.ae"
  },
  {
    "School ID": 241,
    "School Name": "Al Salamat",
    "School Name Arabic": "السلامات",
    "Region": "Al Ain",
    "Address": "AL SALAMAT",
    "GPS_LATITUDE": 24.21133294,
    "GPS_LONGITUDE": 55.59630964,
    "Gender": "M",
    "Alef IT Support Specialist": "Rami Abo Obeid",
    "Alef IT Support Specialist Contact Number": "0509864839",
    "Alef IT Support Specialist Email": "rami@alef.ae",
    "Alef IT Support Team Lead": "Esam Abu Yousif",
    "Alef IT Support Team Lead Contact Number": 565374399,
    "Alef IT Support Team Lead Email": "esam.abuyousif@alef.ae"
  },
  {
    "School ID": 249,
    "School Name": "Hessa Bint Mohamed",
    "School Name Arabic": "حصة بنت محمد",
    "Region": "Al Ain",
    "Address": "ZAKHIR",
    "GPS_LATITUDE": 24.1381,
    "GPS_LONGITUDE": 55.7069,
    "Gender": "F",
    "Alef IT Support Specialist": "Haifa Alkhair Babiker Mohammed",
    "Alef IT Support Specialist Contact Number": "0509867834",
    "Alef IT Support Specialist Email": "haifa@alef.ae (+mai.azzouzova@alef.ae)",
    "Alef IT Support Team Lead": "Samah Ali Ahmad",
    "Alef IT Support Team Lead Contact Number": 564018945,
    "Alef IT Support Team Lead Email": "samah.ali@alef.ae"
  },
  {
    "School ID": 252,
    "School Name": "Bin Ham",
    "School Name Arabic": "بن حم",
    "Region": "Al Ain",
    "Address": "AL WAGAN",
    "GPS_LATITUDE": 23.6389,
    "GPS_LONGITUDE": 55.5451,
    "Gender": "M",
    "Alef IT Support Specialist": "Ahmad Firas Saleh Alkhmour",
    "Alef IT Support Specialist Contact Number": "0505175926",
    "Alef IT Support Specialist Email": "ahmadf.alkhmour@alef.ae",
    "Alef IT Support Team Lead": "Amjad Mohammad Khalil",
    "Alef IT Support Team Lead Contact Number": 509864962,
    "Alef IT Support Team Lead Email": "amjad.khalil@alef.ae"
  },
  {
    "School ID": 260,
    "School Name": "Al Dhahera",
    "School Name Arabic": "الظاهرة",
    "Region": "Al Ain",
    "Address": "AL DHAHRA",
    "GPS_LATITUDE": 24.0005181,
    "GPS_LONGITUDE": 55.57120695,
    "Gender": "M",
    "Alef IT Support Specialist": "Nazar Alaaeldin Ahmed Abdu",
    "Alef IT Support Specialist Contact Number": "0569938742",
    "Alef IT Support Specialist Email": "Nazar.Ahmed@alef.ae",
    "Alef IT Support Team Lead": "Amjad Mohammad Khalil",
    "Alef IT Support Team Lead Contact Number": 509864962,
    "Alef IT Support Team Lead Email": "amjad.khalil@alef.ae"
  },
  {
    "School ID": 262,
    "School Name": "Al Khaznah",
    "School Name Arabic": "الخزنة",
    "Region": "Al Ain",
    "Address": "AL KHAZNAH",
    "GPS_LATITUDE": 24.16753331,
    "GPS_LONGITUDE": 55.11533832,
    "Gender": "M",
    "Alef IT Support Specialist": "Khaled Adnan Saad",
    "Alef IT Support Specialist Contact Number": "0569943603",
    "Alef IT Support Specialist Email": "Khaled.Saad@alef.ae",
    "Alef IT Support Team Lead": "Esam Abu Yousif",
    "Alef IT Support Team Lead Contact Number": 565374399,
    "Alef IT Support Team Lead Email": "esam.abuyousif@alef.ae"
  },
  {
    "School ID": 268,
    "School Name": "Al Showaib",
    "School Name Arabic": "الشويب  ",
    "Region": "Al Ain",
    "Address": "AL SHWAIB",
    "GPS_LATITUDE": 24.7415,
    "GPS_LONGITUDE": 55.7875,
    "Gender": "M",
    "Alef IT Support Specialist": "MOHAMED AHMED MOHAMED AHMED",
    "Alef IT Support Specialist Contact Number": "0505204236",
    "Alef IT Support Specialist Email": "mohamed.ahmeddirar@alef.ae",
    "Alef IT Support Team Lead": "Ahmed Fathi Sayed",
    "Alef IT Support Team Lead Contact Number": 509869037,
    "Alef IT Support Team Lead Email": "ahmed.fathi@alef.ae"
  },
  {
    "School ID": 269,
    "School Name": "Al Tamayoz",
    "School Name Arabic": "التميز",
    "Region": "Al Ain",
    "Address": "FALAJ HAZZA",
    "GPS_LATITUDE": 24.19480695,
    "GPS_LONGITUDE": 55.73551058,
    "Gender": "M",
    "Alef IT Support Specialist": "Abdel Rahman Jamal A.Jubran",
    "Alef IT Support Specialist Contact Number": "0569905132",
    "Alef IT Support Specialist Email": "abdelrahman@alef.ae",
    "Alef IT Support Team Lead": "Ahmed Fathi Sayed",
    "Alef IT Support Team Lead Contact Number": 509869037,
    "Alef IT Support Team Lead Email": "ahmed.fathi@alef.ae"
  },
  {
    "School ID": 272,
    "School Name": "Shakhbout Bin Sultan",
    "School Name Arabic": "شخبوط بن سلطان",
    "Region": "Al Ain",
    "Address": "AL YAHAR",
    "GPS_LATITUDE": 24.2287,
    "GPS_LONGITUDE": 55.5527,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohamed Mahmoud Yahia Mahmoud",
    "Alef IT Support Specialist Contact Number": "0565024506",
    "Alef IT Support Specialist Email": "mohamed.yahia@alef.ae",
    "Alef IT Support Team Lead": "Esam Abu Yousif",
    "Alef IT Support Team Lead Contact Number": 565374399,
    "Alef IT Support Team Lead Email": "esam.abuyousif@alef.ae"
  },
  {
    "School ID": 315,
    "School Name": "Bu Koreyya",
    "School Name Arabic": "بوكرية",
    "Region": "Al Ain",
    "Address": "ABU KRAYYAH",
    "GPS_LATITUDE": 23.88176841,
    "GPS_LONGITUDE": 55.40236093,
    "Gender": "M",
    "Alef IT Support Specialist": "Majid Abdalaziz Abdalrhman Abdalmahmoud",
    "Alef IT Support Specialist Contact Number": "0505204650",
    "Alef IT Support Specialist Email": "Majid.Abdelmahmoud@alef.ae",
    "Alef IT Support Team Lead": "Amjad Mohammad Khalil",
    "Alef IT Support Team Lead Contact Number": 509864962,
    "Alef IT Support Team Lead Email": "amjad.khalil@alef.ae"
  },
  {
    "School ID": 321,
    "School Name": "Sultan Bin Zayed",
    "School Name Arabic": "سلطان بن زايد",
    "Region": "Al Ain",
    "Address": "AL MUTAREDH",
    "GPS_LATITUDE": 24.21959662,
    "GPS_LONGITUDE": 55.73506872,
    "Gender": "M",
    "Alef IT Support Specialist": "Omer Abdelbagi",
    "Alef IT Support Specialist Contact Number": "0564019338",
    "Alef IT Support Specialist Email": "omer@alef.ae",
    "Alef IT Support Team Lead": "Ahmed Fathi Sayed",
    "Alef IT Support Team Lead Contact Number": 509869037,
    "Alef IT Support Team Lead Email": "ahmed.fathi@alef.ae"
  },
  {
    "School ID": 330,
    "School Name": "Al Hayar",
    "School Name Arabic": "الهير",
    "Region": "Al Ain",
    "Address": "AL HAYER",
    "GPS_LATITUDE": 24.6024536,
    "GPS_LONGITUDE": 55.76117151,
    "Gender": "M",
    "Alef IT Support Specialist": "ELHUSSEINY IBRAHIM ABDALLA ELHUSSEIN ABDELKADER",
    "Alef IT Support Specialist Contact Number": "0505181570",
    "Alef IT Support Specialist Email": "ElHusseiny.Abdelkadir@alef.ae",
    "Alef IT Support Team Lead": "Ahmed Fathi Sayed",
    "Alef IT Support Team Lead Contact Number": 509869037,
    "Alef IT Support Team Lead Email": "ahmed.fathi@alef.ae"
  },
  {
    "School ID": 333,
    "School Name": "Al Quaa",
    "School Name Arabic": "القوع",
    "Region": "Al Ain",
    "Address": "AL QUA'A",
    "GPS_LATITUDE": 23.41035761,
    "GPS_LONGITUDE": 55.42590025,
    "Gender": "M",
    "Alef IT Support Specialist": "Eslam Farouk",
    "Alef IT Support Specialist Contact Number": "0505187013",
    "Alef IT Support Specialist Email": "eslam.abdallah@alef.ae",
    "Alef IT Support Team Lead": "Amjad Mohammad Khalil",
    "Alef IT Support Team Lead Contact Number": 509864962,
    "Alef IT Support Team Lead Email": "amjad.khalil@alef.ae"
  },
  {
    "School ID": 337,
    "School Name": "Al Adel",
    "School Name Arabic": "العدل",
    "Region": "Al Ain",
    "Address": "AL YAHAR",
    "GPS_LATITUDE": 24.2277,
    "GPS_LONGITUDE": 55.5563,
    "Gender": "M",
    "Alef IT Support Specialist": "Ibrahim Yousef Mohammed Al Daher",
    "Alef IT Support Specialist Contact Number": "0509865823",
    "Alef IT Support Specialist Email": "ibrahim@alef.ae",
    "Alef IT Support Team Lead": "Esam Abu Yousif",
    "Alef IT Support Team Lead Contact Number": 565374399,
    "Alef IT Support Team Lead Email": "esam.abuyousif@alef.ae"
  },
  {
    "School ID": 338,
    "School Name": "Makkah",
    "School Name Arabic": "مكة",
    "Region": "Al Ain",
    "Address": "AL KHABISI",
    "GPS_LATITUDE": 24.23155056,
    "GPS_LONGITUDE": 55.68316021,
    "Gender": "F",
    "Alef IT Support Specialist": "Doaa A. K. Arafat",
    "Alef IT Support Specialist Contact Number": "0565015951",
    "Alef IT Support Specialist Email": "doaa.a@alef.ae",
    "Alef IT Support Team Lead": "Lulwa bin eshaq",
    "Alef IT Support Team Lead Contact Number": 509867810,
    "Alef IT Support Team Lead Email": "lulwa@alef.ae"
  },
  {
    "School ID": 350,
    "School Name": "Ibn Khaldoon",
    "School Name Arabic": "ابن خلدون",
    "Region": "Al Ain",
    "Address": "AL SAROOJ",
    "GPS_LATITUDE": 24.2043,
    "GPS_LONGITUDE": 55.7957,
    "Gender": "M",
    "Alef IT Support Specialist": "Suliman Siddig Mohamedzein Abdalla",
    "Alef IT Support Specialist Contact Number": "0569942962",
    "Alef IT Support Specialist Email": "Suliman.Abdalla@alef.ae",
    "Alef IT Support Team Lead": "Amjad Mohammad Khalil",
    "Alef IT Support Team Lead Contact Number": 509864962,
    "Alef IT Support Team Lead Email": "amjad.khalil@alef.ae"
  },
  {
    "School ID": 354,
    "School Name": "Al Dahmaa",
    "School Name Arabic": "الدهماء",
    "Region": "Al Ain",
    "Address": "AL BATEEN",
    "GPS_LATITUDE": 24.2157,
    "GPS_LONGITUDE": 55.6375,
    "Gender": "M",
    "Alef IT Support Specialist": "Adnan Hammad Hassan Ayyash",
    "Alef IT Support Specialist Contact Number": "0505175618",
    "Alef IT Support Specialist Email": "Adnan.Ayyash@alef.ae",
    "Alef IT Support Team Lead": "Amjad Mohammad Khalil",
    "Alef IT Support Team Lead Contact Number": 509864962,
    "Alef IT Support Team Lead Email": "amjad.khalil@alef.ae"
  },
  {
    "School ID": 359,
    "School Name": "Salama Bint Butti",
    "School Name Arabic": "سلامة بنت بطي",
    "Region": "Al Ain",
    "Address": "AL SALAMAT",
    "GPS_LATITUDE": 24.2037,
    "GPS_LONGITUDE": 55.5881,
    "Gender": "F",
    "Alef IT Support Specialist": "Islam Alhag Ibrahim",
    "Alef IT Support Specialist Contact Number": "0569903193",
    "Alef IT Support Specialist Email": "Islam.alhag@alef.ae",
    "Alef IT Support Team Lead": "Wala El Rashied Suliman",
    "Alef IT Support Team Lead Contact Number": 509869673,
    "Alef IT Support Team Lead Email": "wala@alef.ae"
  },
  {
    "School ID": 366,
    "School Name": "Al Danat",
    "School Name Arabic": "الدانات",
    "Region": "Al Ain",
    "Address": "AL QUA'A",
    "GPS_LATITUDE": 23.41789299,
    "GPS_LONGITUDE": 55.42012091,
    "Gender": "F",
    "Alef IT Support Specialist": "Naama Babiker Ahmed",
    "Alef IT Support Specialist Contact Number": "0566893532",
    "Alef IT Support Specialist Email": "naama.abdallah@alef.ae",
    "Alef IT Support Team Lead": "Samah Ali Ahmad",
    "Alef IT Support Team Lead Contact Number": 564018945,
    "Alef IT Support Team Lead Email": "samah.ali@alef.ae"
  },
  {
    "School ID": 376,
    "School Name": "Sweihan",
    "School Name Arabic": "سويحان",
    "Region": "Al Ain",
    "Address": "SWEIHAN",
    "GPS_LATITUDE": 24.46526763,
    "GPS_LONGITUDE": 55.33013557,
    "Gender": "M",
    "Alef IT Support Specialist": "Laith Rasmi Ass'ad Ghawi",
    "Alef IT Support Specialist Contact Number": "0505187339",
    "Alef IT Support Specialist Email": "Laith.Ghawi@alef.ae",
    "Alef IT Support Team Lead": "Esam Abu Yousif",
    "Alef IT Support Team Lead Contact Number": 565374399,
    "Alef IT Support Team Lead Email": "esam.abuyousif@alef.ae"
  },
  {
    "School ID": 406,
    "School Name": "Al Naeem",
    "School Name Arabic": "النعيم",
    "Region": "Al Ain",
    "Address": "AL YAHAR",
    "GPS_LATITUDE": 24.2333,
    "GPS_LONGITUDE": 55.5501,
    "Gender": "F",
    "Alef IT Support Specialist": "Leena Osama Fahmi Saqer",
    "Alef IT Support Specialist Contact Number": "0505193946",
    "Alef IT Support Specialist Email": "Leena.Saqer@alef.ae",
    "Alef IT Support Team Lead": "Wala El Rashied Suliman",
    "Alef IT Support Team Lead Contact Number": 509869673,
    "Alef IT Support Team Lead Email": "wala@alef.ae"
  },
  {
    "School ID": 411,
    "School Name": "Al Refaah",
    "School Name Arabic": "الرفعة",
    "Region": "Al Ain",
    "Address": "AL HAYER",
    "GPS_LATITUDE": 24.6037,
    "GPS_LONGITUDE": 55.7555,
    "Gender": "F",
    "Alef IT Support Specialist": "Nada Mohamed Obaid",
    "Alef IT Support Specialist Contact Number": "0562362922",
    "Alef IT Support Specialist Email": "nada.obaid@alef.ae",
    "Alef IT Support Team Lead": "Lulwa bin eshaq",
    "Alef IT Support Team Lead Contact Number": 509867810,
    "Alef IT Support Team Lead Email": "lulwa@alef.ae"
  },
  {
    "School ID": 420,
    "School Name": "Al Badiyah",
    "School Name Arabic": "البادية",
    "Region": "Al Ain",
    "Address": "AL WAGAN",
    "GPS_LATITUDE": 23.6313,
    "GPS_LONGITUDE": 55.5527,
    "Gender": "F",
    "Alef IT Support Specialist": "Dwa Mohamed Zeyab Abushabab",
    "Alef IT Support Specialist Contact Number": "0547932997",
    "Alef IT Support Specialist Email": "dwa.abushabab@alef.ae",
    "Alef IT Support Team Lead": "Samah Ali Ahmad",
    "Alef IT Support Team Lead Contact Number": 564018945,
    "Alef IT Support Team Lead Email": "samah.ali@alef.ae"
  },
  {
    "School ID": 427,
    "School Name": "Al Sariyah",
    "School Name Arabic": "السارية",
    "Region": "Al Ain",
    "Address": "SWEIHAN",
    "GPS_LATITUDE": 24.46529299,
    "GPS_LONGITUDE": 55.34251428,
    "Gender": "0",
    "Alef IT Support Specialist": "Wafa Fadlallah Alzain Dafaalla",
    "Alef IT Support Specialist Contact Number": "0566893637",
    "Alef IT Support Specialist Email": "Wafa.Dafaalla@alef.ae",
    "Alef IT Support Team Lead": "Lulwa bin eshaq",
    "Alef IT Support Team Lead Contact Number": 509867810,
    "Alef IT Support Team Lead Email": "lulwa@alef.ae"
  },
  {
    "School ID": 431,
    "School Name": "Um Ayman Bint Thaalaba",
    "School Name Arabic": "مدرسة أم أيمن بنت ثعلبة",
    "Region": "Al Ain",
    "Address": "Falaj Hazza",
    "GPS_LATITUDE": 24.1853,
    "GPS_LONGITUDE": 55.7149,
    "Gender": "F",
    "Alef IT Support Specialist": "ASMAA ATIF HASAN NASSAR",
    "Alef IT Support Specialist Contact Number": "0549946030",
    "Alef IT Support Specialist Email": "asmaa.nassar@alef.ae",
    "Alef IT Support Team Lead": "Lulwa bin eshaq",
    "Alef IT Support Team Lead Contact Number": 509867810,
    "Alef IT Support Team Lead Email": "lulwa@alef.ae"
  },
  {
    "School ID": 446,
    "School Name": "TARIQ BIN ZIAD",
    "School Name Arabic": "طارق بن زياد",
    "Region": "Al Ain",
    "Address": "AL MAQAM",
    "GPS_LATITUDE": 24.1819,
    "GPS_LONGITUDE": 55.6123,
    "Gender": "F",
    "Alef IT Support Specialist": "Muna Khalil Ibrahim Awad (+Youstina Kamel Asaad Kamel)",
    "Alef IT Support Specialist Contact Number": "0569938020 (+0562548802)",
    "Alef IT Support Specialist Email": "Muna.Awad@alef.ae (youstina.kamel@alef.ae)",
    "Alef IT Support Team Lead": "Wala El Rashied Suliman",
    "Alef IT Support Team Lead Contact Number": 509869673,
    "Alef IT Support Team Lead Email": "wala@alef.ae"
  },
  {
    "School ID": 459,
    "School Name": "Al Maqam",
    "School Name Arabic": "المقام",
    "Region": "Al Ain",
    "Address": "AL MAQAM",
    "GPS_LATITUDE": 24.1893928,
    "GPS_LONGITUDE": 55.62481803,
    "Gender": "M",
    "Alef IT Support Specialist": "Osama Osman Mohamed Babiker",
    "Alef IT Support Specialist Contact Number": "0569940826",
    "Alef IT Support Specialist Email": "Osama.Osman@alef.ae",
    "Alef IT Support Team Lead": "Esam Abu Yousif",
    "Alef IT Support Team Lead Contact Number": 565374399,
    "Alef IT Support Team Lead Email": "esam.abuyousif@alef.ae"
  },
  {
    "School ID": 466,
    "School Name": "Al Tafawoq",
    "School Name Arabic": "التفوق",
    "Region": "Al Ain",
    "Address": "HILI",
    "GPS_LATITUDE": 24.30117533,
    "GPS_LONGITUDE": 55.79403219,
    "Gender": "M",
    "Alef IT Support Specialist": "Maisra Saad Mohamed",
    "Alef IT Support Specialist Contact Number": "0569952176",
    "Alef IT Support Specialist Email": "maisra.saad@alef.ae",
    "Alef IT Support Team Lead": "Ahmed Fathi Sayed",
    "Alef IT Support Team Lead Contact Number": 509869037,
    "Alef IT Support Team Lead Email": "ahmed.fathi@alef.ae"
  },
  {
    "School ID": 470,
    "School Name": "Al Ataa",
    "School Name Arabic": "العطاء",
    "Region": "Al Ain",
    "Address": "AL DHAHRA",
    "GPS_LATITUDE": 23.99838554,
    "GPS_LONGITUDE": 55.57256807,
    "Gender": "F",
    "Alef IT Support Specialist": "Taghreed K. M. Madi",
    "Alef IT Support Specialist Contact Number": "0569942985",
    "Alef IT Support Specialist Email": "Taghreed.Madi@alef.ae",
    "Alef IT Support Team Lead": "Samah Ali Ahmad",
    "Alef IT Support Team Lead Contact Number": 564018945,
    "Alef IT Support Team Lead Email": "samah.ali@alef.ae"
  },
  {
    "School ID": 484,
    "School Name": "AL GHAITH",
    "School Name Arabic": "الغيث",
    "Region": "Al Ain",
    "Address": "AL MAQAM",
    "GPS_LATITUDE": 24.1879,
    "GPS_LONGITUDE": 55.6255,
    "Gender": "F",
    "Alef IT Support Specialist": "HIND MAGDI HAMZA BALDO",
    "Alef IT Support Specialist Contact Number": "0505185084",
    "Alef IT Support Specialist Email": "Hind.Baldo@alef.ae",
    "Alef IT Support Team Lead": "Samah Ali Ahmad",
    "Alef IT Support Team Lead Contact Number": 564018945,
    "Alef IT Support Team Lead Email": "samah.ali@alef.ae"
  },
  {
    "School ID": 492,
    "School Name": "Al Ain Model",
    "School Name Arabic": "العين النموذجية",
    "Region": "Al Ain",
    "Address": "HILI",
    "GPS_LATITUDE": 24.288676453,
    "GPS_LONGITUDE": 55.766205823,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohamed Mahmoud Sharif",
    "Alef IT Support Specialist Contact Number": "0564008534",
    "Alef IT Support Specialist Email": "msharif@alef.ae",
    "Alef IT Support Team Lead": "Ahmed Fathi Sayed",
    "Alef IT Support Team Lead Contact Number": 509869037,
    "Alef IT Support Team Lead Email": "ahmed.fathi@alef.ae"
  },
  {
    "School ID": 496,
    "School Name": "Al Hemma",
    "School Name Arabic": "الهمة",
    "Region": "Al Ain",
    "Address": "AL MAQAM",
    "GPS_LATITUDE": 24.1825,
    "GPS_LONGITUDE": 55.6151,
    "Gender": "F",
    "Alef IT Support Specialist": "Muna Khalil Ibrahim Awad",
    "Alef IT Support Specialist Contact Number": "0569938020",
    "Alef IT Support Specialist Email": "Muna.Awad@alef.ae",
    "Alef IT Support Team Lead": "Wala El Rashied Suliman",
    "Alef IT Support Team Lead Contact Number": 509869673,
    "Alef IT Support Team Lead Email": "wala@alef.ae"
  },
  {
    "School ID": 500,
    "School Name": "Um Kolthoom",
    "School Name Arabic": "أم كلثوم",
    "Region": "Al Ain",
    "Address": "AL MAQAM",
    "GPS_LATITUDE": 24.18656043,
    "GPS_LONGITUDE": 55.62126074,
    "Gender": "F",
    "Alef IT Support Specialist": "HIND MAGDI HAMZA BALDO",
    "Alef IT Support Specialist Contact Number": "0505185084",
    "Alef IT Support Specialist Email": "Hind.Baldo@alef.ae",
    "Alef IT Support Team Lead": "Samah Ali Ahmad",
    "Alef IT Support Team Lead Contact Number": 564018945,
    "Alef IT Support Team Lead Email": "samah.ali@alef.ae"
  },
  {
    "School ID": 501,
    "School Name": "Al Taleaa",
    "School Name Arabic": "الطليعة",
    "Region": "Al Ain",
    "Address": "REMAH",
    "GPS_LATITUDE": 24.20338209,
    "GPS_LONGITUDE": 55.33213582,
    "Gender": "F",
    "Alef IT Support Specialist": "Aya Rizik Abu Shawish",
    "Alef IT Support Specialist Contact Number": "0569943744",
    "Alef IT Support Specialist Email": "Aya.Rizik@alef.ae",
    "Alef IT Support Team Lead": "Wala El Rashied Suliman",
    "Alef IT Support Team Lead Contact Number": 509869673,
    "Alef IT Support Team Lead Email": "wala@alef.ae"
  },
  {
    "School ID": 520,
    "School Name": "Khaled Bin Al Waleed",
    "School Name Arabic": "خالد بن الوليد",
    "Region": "Al Ain",
    "Address": "AL SAROOJ",
    "GPS_LATITUDE": 24.1921,
    "GPS_LONGITUDE": 55.7911,
    "Gender": "M",
    "Alef IT Support Specialist": "Ahmed Mohammed Elamin Abdelrahman Mohamed",
    "Alef IT Support Specialist Contact Number": "0505178002",
    "Alef IT Support Specialist Email": "Ahmed.Elamin@alef.ae",
    "Alef IT Support Team Lead": "Amjad Mohammad Khalil",
    "Alef IT Support Team Lead Contact Number": 509864962,
    "Alef IT Support Team Lead Email": "amjad.khalil@alef.ae"
  },
  {
    "School ID": 523,
    "School Name": "Um Al Emarat (Al Ain)",
    "School Name Arabic": "أم الإمارات",
    "Region": "Al Ain",
    "Address": "HILI",
    "GPS_LATITUDE": 24.273918355,
    "GPS_LONGITUDE": 55.76410144,
    "Gender": "F",
    "Alef IT Support Specialist": "ELHAM K.A.SERRIA",
    "Alef IT Support Specialist Contact Number": "0505181342",
    "Alef IT Support Specialist Email": "Elham.ASerria@alef.ae",
    "Alef IT Support Team Lead": "Samah Ali Ahmad",
    "Alef IT Support Team Lead Contact Number": 564018945,
    "Alef IT Support Team Lead Email": "samah.ali@alef.ae"
  },
  {
    "School ID": 527,
    "School Name": "Tahnoon Bin Mohamed",
    "School Name Arabic": "طحنون بن محمد",
    "Region": "Al Ain",
    "Address": "ZAKHIR",
    "GPS_LATITUDE": 24.1357,
    "GPS_LONGITUDE": 55.6977,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohanad Alsayed",
    "Alef IT Support Specialist Contact Number": "0509866324",
    "Alef IT Support Specialist Email": "mohanad@alef.ae",
    "Alef IT Support Team Lead": "Ahmed Fathi Sayed",
    "Alef IT Support Team Lead Contact Number": 509869037,
    "Alef IT Support Team Lead Email": "ahmed.fathi@alef.ae"
  },
  {
    "School ID": 533,
    "School Name": "Al Bedaa",
    "School Name Arabic": "البدع",
    "Region": "Al Ain",
    "Address": "NAHEL TOWN",
    "GPS_LATITUDE": 24.5103,
    "GPS_LONGITUDE": 55.4899,
    "Gender": "M",
    "Alef IT Support Specialist": "Hamza Ahmad Abu saleh",
    "Alef IT Support Specialist Contact Number": "0505183491",
    "Alef IT Support Specialist Email": "Hamza.Abusaleh@alef.ae",
    "Alef IT Support Team Lead": "Esam Abu Yousif",
    "Alef IT Support Team Lead Contact Number": 565374399,
    "Alef IT Support Team Lead Email": "esam.abuyousif@alef.ae"
  },
  {
    "School ID": 535,
    "School Name": "Nahel",
    "School Name Arabic": "ناهل",
    "Region": "Al Ain",
    "Address": "NAHEL TOWN",
    "GPS_LATITUDE": 24.51963932,
    "GPS_LONGITUDE": 55.53812117,
    "Gender": "F",
    "Alef IT Support Specialist": "Basma Mohamad Alfetuhi Aljendi",
    "Alef IT Support Specialist Contact Number": "0505179274",
    "Alef IT Support Specialist Email": "Basma.Aljendi@alef.ae",
    "Alef IT Support Team Lead": "Lulwa bin eshaq",
    "Alef IT Support Team Lead Contact Number": 509867810,
    "Alef IT Support Team Lead Email": "lulwa@alef.ae"
  },
  {
    "School ID": 539,
    "School Name": "Um Al Fadhel Bint Al Hareth",
    "School Name Arabic": "أم الفضل بنت الحارث",
    "Region": "Al Ain",
    "Address": "AL YAHAR",
    "GPS_LATITUDE": 24.23352405,
    "GPS_LONGITUDE": 55.55202874,
    "Gender": "F",
    "Alef IT Support Specialist": "Dima Mahmoud Alodeh",
    "Alef IT Support Specialist Contact Number": "0509865218",
    "Alef IT Support Specialist Email": "dima.mahmoud@alef.ae",
    "Alef IT Support Team Lead": "Wala El Rashied Suliman",
    "Alef IT Support Team Lead Contact Number": 509869673,
    "Alef IT Support Team Lead Email": "wala@alef.ae"
  },
  {
    "School ID": 542,
    "School Name": "Al Resalah",
    "School Name Arabic": "الرسالة",
    "Region": "Al Ain",
    "Address": "AL FAQA'A",
    "GPS_LATITUDE": 24.7163,
    "GPS_LONGITUDE": 55.6171,
    "Gender": "F",
    "Alef IT Support Specialist": "Maysoon Ali Mohamed",
    "Alef IT Support Specialist Contact Number": "0569952175",
    "Alef IT Support Specialist Email": "maysoon.ali@alef.ae",
    "Alef IT Support Team Lead": "Lulwa bin eshaq",
    "Alef IT Support Team Lead Contact Number": 509867810,
    "Alef IT Support Team Lead Email": "lulwa@alef.ae"
  },
  {
    "School ID": 543,
    "School Name": "Al Borooj",
    "School Name Arabic": "البروج",
    "Region": "Al Ain",
    "Address": "ABU KRAYYAH",
    "GPS_LATITUDE": 23.87988096,
    "GPS_LONGITUDE": 55.39397652,
    "Gender": "F",
    "Alef IT Support Specialist": "Rahaf Zeyad Suleiman Shatnawi",
    "Alef IT Support Specialist Contact Number": "0505195782",
    "Alef IT Support Specialist Email": "rahaf.shatnawi@alef.ae",
    "Alef IT Support Team Lead": "Samah Ali Ahmad",
    "Alef IT Support Team Lead Contact Number": 564018945,
    "Alef IT Support Team Lead Email": "samah.ali@alef.ae"
  },
  {
    "School ID": 553,
    "School Name": "Atika Bint Abdel Muttalib",
    "School Name Arabic": "عاتكة بنت عبدالمطلب",
    "Region": "Al Ain",
    "Address": "AL SAROOJ",
    "GPS_LATITUDE": 24.20262887,
    "GPS_LONGITUDE": 55.77472392,
    "Gender": "F",
    "Alef IT Support Specialist": "Hend Mohamed Mohamedy Abdallah Seada",
    "Alef IT Support Specialist Contact Number": "0569904859",
    "Alef IT Support Specialist Email": "hend.mohamed@alef.ae",
    "Alef IT Support Team Lead": "Samah Ali Ahmad",
    "Alef IT Support Team Lead Contact Number": 564018945,
    "Alef IT Support Team Lead Email": "samah.ali@alef.ae"
  },
  {
    "School ID": 1077,
    "School Name": "Al Mabade",
    "School Name Arabic": "المبادئ",
    "Region": "Al Ain",
    "Address": "AL KHAZNAH",
    "GPS_LATITUDE": 24.16079493,
    "GPS_LONGITUDE": 55.13057138,
    "Gender": "F",
    "Alef IT Support Specialist": "Aliaa Galal Ahmed Hashem",
    "Alef IT Support Specialist Contact Number": "0505178153",
    "Alef IT Support Specialist Email": "Aliaa.Galal@alef.ae",
    "Alef IT Support Team Lead": "Wala El Rashied Suliman",
    "Alef IT Support Team Lead Contact Number": 509869673,
    "Alef IT Support Team Lead Email": "wala@alef.ae"
  },
  {
    "School ID": 1082,
    "School Name": "Al Dhaher",
    "School Name Arabic": "الظاهر",
    "Region": "Al Ain",
    "Address": "AL DHAHER",
    "GPS_LATITUDE": 24.08675986,
    "GPS_LONGITUDE": 55.86667621,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohamed Murtada (+ Ibrahim Saber",
    "Alef IT Support Specialist Contact Number": "0564019300",
    "Alef IT Support Specialist Email": "mohamed.murtada@alef.ae (+ ibrahim.elhusseini@alef.ae)",
    "Alef IT Support Team Lead": "Ahmed Fathi Sayed",
    "Alef IT Support Team Lead Contact Number": 509869037,
    "Alef IT Support Team Lead Email": "ahmed.fathi@alef.ae"
  },
  {
    "School ID": 1083,
    "School Name": "Al Hosoon",
    "School Name Arabic": "الحصون",
    "Region": "Al Ain",
    "Address": "MEZYAD",
    "GPS_LATITUDE": 24.0483,
    "GPS_LONGITUDE": 55.8435,
    "Gender": "F",
    "Alef IT Support Specialist": "Shimaa Faysal Awad Ibrahim",
    "Alef IT Support Specialist Contact Number": "0509868269",
    "Alef IT Support Specialist Email": "shimaa@alef.ae",
    "Alef IT Support Team Lead": "Wala El Rashied Suliman",
    "Alef IT Support Team Lead Contact Number": 509869673,
    "Alef IT Support Team Lead Email": "wala@alef.ae"
  },
  {
    "School ID": 1085,
    "School Name": "Al Shiyam",
    "School Name Arabic": "الشيم",
    "Region": "Al Ain",
    "Address": "UM GHAFFA",
    "GPS_LATITUDE": 24.09925016,
    "GPS_LONGITUDE": 55.90588096,
    "Gender": "F",
    "Alef IT Support Specialist": "MAYADA KHALIL OSMAN",
    "Alef IT Support Specialist Contact Number": "0509869619",
    "Alef IT Support Specialist Email": "mayada@alef.ae",
    "Alef IT Support Team Lead": "Wala El Rashied Suliman",
    "Alef IT Support Team Lead Contact Number": 509869673,
    "Alef IT Support Team Lead Email": "wala@alef.ae"
  },
  {
    "School ID": 1086,
    "School Name": "Maryam Bint Sultan",
    "School Name Arabic": "مريم بنت سلطان",
    "Region": "Al Ain",
    "Address": "AL TOWAYYA",
    "GPS_LATITUDE": 24.25864966,
    "GPS_LONGITUDE": 55.70596663,
    "Gender": "F",
    "Alef IT Support Specialist": "Khlood Shaban Ashour",
    "Alef IT Support Specialist Contact Number": "0505187053",
    "Alef IT Support Specialist Email": "Khlood.Ashour@alef.ae",
    "Alef IT Support Team Lead": "Wala El Rashied Suliman",
    "Alef IT Support Team Lead Contact Number": 509869673,
    "Alef IT Support Team Lead Email": "wala@alef.ae"
  },
  {
    "School ID": 1087,
    "School Name": "Al Jahili",
    "School Name Arabic": "الجاهلي",
    "Region": "Al Ain",
    "Address": "AL JAHILI",
    "GPS_LATITUDE": 24.20845028,
    "GPS_LONGITUDE": 55.74809512,
    "Gender": "F",
    "Alef IT Support Specialist": "Mariam Said Sabry Habib",
    "Alef IT Support Specialist Contact Number": "0505205340",
    "Alef IT Support Specialist Email": "Mariam.Sabry@alef.ae",
    "Alef IT Support Team Lead": "Samah Ali Ahmad",
    "Alef IT Support Team Lead Contact Number": 564018945,
    "Alef IT Support Team Lead Email": "samah.ali@alef.ae"
  },
  {
    "School ID": 1089,
    "School Name": "Um Ghafa",
    "School Name Arabic": "ام غافة",
    "Region": "Al Ain",
    "Address": "UM GHAFFA",
    "GPS_LATITUDE": 24.09189274,
    "GPS_LONGITUDE": 55.89701209,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohammed Abaker Morsal Alradi",
    "Alef IT Support Specialist Contact Number": "0565024486",
    "Alef IT Support Specialist Email": "mohammed.alradi@alef.ae",
    "Alef IT Support Team Lead": "Amjad Mohammad Khalil",
    "Alef IT Support Team Lead Contact Number": 509864962,
    "Alef IT Support Team Lead Email": "amjad.khalil@alef.ae"
  },
  {
    "School ID": 1173,
    "School Name": "Al Muraijib",
    "School Name Arabic": "مريجب",
    "Region": "Al Ain",
    "Address": "AL JIMI",
    "GPS_LATITUDE": 24.2533,
    "GPS_LONGITUDE": 55.7227,
    "Gender": "F",
    "Alef IT Support Specialist": "Noor Yahya Taha",
    "Alef IT Support Specialist Contact Number": "0509868256",
    "Alef IT Support Specialist Email": "noor.yahya@alef.ae",
    "Alef IT Support Team Lead": "Lulwa bin eshaq",
    "Alef IT Support Team Lead Contact Number": 509867810,
    "Alef IT Support Team Lead Email": "lulwa@alef.ae"
  },
  {
    "School ID": 1391,
    "School Name": "AHMED BIN ZAYED",
    "School Name Arabic": "أحمد بن زايد",
    "Region": "Al Ain",
    "Address": "ZAKHIR",
    "GPS_LATITUDE": 24.14679305,
    "GPS_LONGITUDE": 55.69074245,
    "Gender": "0",
    "Alef IT Support Specialist": "Islam Gamal Abdelmagid Ismail",
    "Alef IT Support Specialist Contact Number": "0505187495",
    "Alef IT Support Specialist Email": "Islam.Abdelmaged@alef.ae",
    "Alef IT Support Team Lead": "Amjad Mohammad Khalil",
    "Alef IT Support Team Lead Contact Number": 509864962,
    "Alef IT Support Team Lead Email": "amjad.khalil@alef.ae"
  },
  {
    "School ID": 1398,
    "School Name": "Al Foaa",
    "School Name Arabic": "مدرسة الفوعة",
    "Region": "Al Ain",
    "Address": "AL FOAH",
    "GPS_LATITUDE": 24.3421,
    "GPS_LONGITUDE": 55.7999,
    "Gender": "F",
    "Alef IT Support Specialist": "Maha Abd Elrhman Eltoum Ahmed",
    "Alef IT Support Specialist Contact Number": "0509869634",
    "Alef IT Support Specialist Email": "maha.abd@alef.ae",
    "Alef IT Support Team Lead": "Lulwa bin eshaq",
    "Alef IT Support Team Lead Contact Number": 509867810,
    "Alef IT Support Team Lead Email": "lulwa@alef.ae"
  },
  {
    "School ID": 1399,
    "School Name": "Ali Bin Abi Taleb",
    "School Name Arabic": "مدرسة علي بن ابي طالب",
    "Region": "Al Ain",
    "Address": "AL FOAH",
    "GPS_LATITUDE": 24.33911415,
    "GPS_LONGITUDE": 55.80143231,
    "Gender": "M",
    "Alef IT Support Specialist": "Ayman Mohamed Ahmed Hassan",
    "Alef IT Support Specialist Contact Number": "0505178458",
    "Alef IT Support Specialist Email": "Ayman.Hassan@alef.ae",
    "Alef IT Support Team Lead": "Ahmed Fathi Sayed",
    "Alef IT Support Team Lead Contact Number": 509869037,
    "Alef IT Support Team Lead Email": "ahmed.fathi@alef.ae"
  },
  {
    "School ID": 1704,
    "School Name": "NEIMA-C1",
    "School Name Arabic": "نعمة",
    "Region": "Al Ain",
    "Address": "NEIMA",
    "GPS_LATITUDE": 24.10862,
    "GPS_LONGITUDE": 55.70481,
    "Gender": "F",
    "Alef IT Support Specialist": "Hind Abdelrahim Almubarak Eltayed",
    "Alef IT Support Specialist Contact Number": "0562474986",
    "Alef IT Support Specialist Email": "hind.eltayeb@alef.ae",
    "Alef IT Support Team Lead": "Samah Ali Ahmad",
    "Alef IT Support Team Lead Contact Number": 564018945,
    "Alef IT Support Team Lead Email": "samah.ali@alef.ae"
  },
  {
    "School ID": 1726,
    "School Name": "Al Maseera",
    "School Name Arabic": "المسيرة",
    "Region": "Al Ain",
    "Address": "AL SHWAIB",
    "GPS_LATITUDE": 24.7361,
    "GPS_LONGITUDE": 55.7816,
    "Gender": "0",
    "Alef IT Support Specialist": "SAMAR USSAMA ABDELGALIL MOHAMED",
    "Alef IT Support Specialist Contact Number": "0549944833",
    "Alef IT Support Specialist Email": "samar.mohamed@alef.ae",
    "Alef IT Support Team Lead": "Lulwa bin eshaq",
    "Alef IT Support Team Lead Contact Number": 509867810,
    "Alef IT Support Team Lead Email": "lulwa@alef.ae"
  },
  {
    "School ID": 1997,
    "School Name": "Al Khair",
    "School Name Arabic": "الخير",
    "Region": "Al Ain",
    "Address": "AL YAHAR",
    "GPS_LATITUDE": 24.194826744,
    "GPS_LONGITUDE": 55.531376711,
    "Gender": "F",
    "Alef IT Support Specialist": "SAHER SHAREEF HASSAN IBNOOF",
    "Alef IT Support Specialist Contact Number": "0509870149",
    "Alef IT Support Specialist Email": "saher.ibnoof@alef.ae",
    "Alef IT Support Team Lead": "Lulwa bin eshaq",
    "Alef IT Support Team Lead Contact Number": 509867810,
    "Alef IT Support Team Lead Email": "lulwa@alef.ae"
  },
  {
    "School ID": 2002,
    "School Name": "Al Nebras",
    "School Name Arabic": "النبراس",
    "Region": "Al Ain",
    "Address": "AL SALAMAT",
    "GPS_LATITUDE": 24.212271622,
    "GPS_LONGITUDE": 55.587395735,
    "Gender": "M",
    "Alef IT Support Specialist": "Moin M.K. Shurrab",
    "Alef IT Support Specialist Contact Number": "0565024507",
    "Alef IT Support Specialist Email": "Moin.Shurrab@alef.ae",
    "Alef IT Support Team Lead": "Esam Abu Yousif",
    "Alef IT Support Team Lead Contact Number": 565374399,
    "Alef IT Support Team Lead Email": "esam.abuyousif@alef.ae"
  },
  {
    "School ID": 2028,
    "School Name": "NEIMA-C2",
    "School Name Arabic": "نعمة",
    "Region": "Al Ain",
    "Address": "NEIMA",
    "GPS_LATITUDE": 24.110917,
    "GPS_LONGITUDE": 55.708563,
    "Gender": "M",
    "Alef IT Support Specialist": "Ahmad Izzaldien Osman Adam",
    "Alef IT Support Specialist Contact Number": "0509870563",
    "Alef IT Support Specialist Email": "ahmad.izzaldien@alef.ae",
    "Alef IT Support Team Lead": "Ahmed Fathi Sayed",
    "Alef IT Support Team Lead Contact Number": 509869037,
    "Alef IT Support Team Lead Email": "ahmed.fathi@alef.ae"
  },
  {
    "School ID": 2029,
    "School Name": "New Al Dhaher",
    "School Name Arabic": "الظاهر الجديدة",
    "Region": "Al Ain",
    "Address": "AL DHAHER",
    "GPS_LATITUDE": 24.075688,
    "GPS_LONGITUDE": 55.84107,
    "Gender": "F",
    "Alef IT Support Specialist": "Mai Azzouzova",
    "Alef IT Support Specialist Contact Number": "0565044568",
    "Alef IT Support Specialist Email": "mai.azzouzova@alef.ae",
    "Alef IT Support Team Lead": "Wala El Rashied Suliman",
    "Alef IT Support Team Lead Contact Number": 509869673,
    "Alef IT Support Team Lead Email": "wala@alef.ae"
  },
  {
    "School ID": 282,
    "School Name": "Qatr Al Nada",
    "School Name Arabic": "قطر الندى",
    "Region": "Al Dhafra",
    "Address": "MADINAT ZAYED",
    "GPS_LATITUDE": 23.6479,
    "GPS_LONGITUDE": 53.7105,
    "Gender": "F",
    "Alef IT Support Specialist": "Riham F. S. Alhajjar + (Rahma Gamal Ibrahim)",
    "Alef IT Support Specialist Contact Number": "0566894315",
    "Alef IT Support Specialist Email": "riham.alhajjar@alef.ae (+ rahma.farahat@alef.ae)",
    "Alef IT Support Team Lead": "Marwa Ahmed Ibrahim Ahmed Gheith",
    "Alef IT Support Team Lead Contact Number": 505207391,
    "Alef IT Support Team Lead Email": "marwa.gheith@alef.ae"
  },
  {
    "School ID": 285,
    "School Name": "Al Seddique",
    "School Name Arabic": "الصديق",
    "Region": "Al Dhafra",
    "Address": "LIWA",
    "GPS_LATITUDE": 23.1215,
    "GPS_LONGITUDE": 53.9223,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohamed Tom Ahmed Widatalla Elshaib",
    "Alef IT Support Specialist Contact Number": "0505199489",
    "Alef IT Support Specialist Email": "Mohammed.Tom@alef.ae",
    "Alef IT Support Team Lead": "Anas Mamoun Eid Kamar",
    "Alef IT Support Team Lead Contact Number": 509869405,
    "Alef IT Support Team Lead Email": "anas.mamoun@alef.ae"
  },
  {
    "School ID": 438,
    "School Name": "Al Farooq",
    "School Name Arabic": "الفاروق",
    "Region": "Al Dhafra",
    "Address": "LIWA",
    "GPS_LATITUDE": 23.1149,
    "GPS_LONGITUDE": 53.6019,
    "Gender": "M",
    "Alef IT Support Specialist": "Ahmed Abobker Mohamed Salih",
    "Alef IT Support Specialist Contact Number": "0505178101",
    "Alef IT Support Specialist Email": "ahmed.salih@alef.ae",
    "Alef IT Support Team Lead": "Anas Mamoun Eid Kamar",
    "Alef IT Support Team Lead Contact Number": 509869405,
    "Alef IT Support Team Lead Email": "anas.mamoun@alef.ae"
  },
  {
    "School ID": 507,
    "School Name": "Al Abbas Bin Abdul Muttalib",
    "School Name Arabic": "العباس بن عبدالمطلب",
    "Region": "Al Dhafra",
    "Address": "AL RUWAIS",
    "GPS_LATITUDE": 24.07529405,
    "GPS_LONGITUDE": 52.64445467,
    "Gender": "M",
    "Alef IT Support Specialist": "Khaled Al-Hashem",
    "Alef IT Support Specialist Contact Number": "0564019709",
    "Alef IT Support Specialist Email": "khaled.hashem@alef.ae",
    "Alef IT Support Team Lead": "Anas Mamoun Eid Kamar",
    "Alef IT Support Team Lead Contact Number": 509869405,
    "Alef IT Support Team Lead Email": "anas.mamoun@alef.ae"
  },
  {
    "School ID": 526,
    "School Name": "Al Mottahida",
    "School Name Arabic": "المتحدة",
    "Region": "Al Dhafra",
    "Address": "GHAYATHI",
    "GPS_LATITUDE": 23.83592226,
    "GPS_LONGITUDE": 52.81089252,
    "Gender": "F",
    "Alef IT Support Specialist": "Salwa Falah Khalaf",
    "Alef IT Support Specialist Contact Number": "0569943461",
    "Alef IT Support Specialist Email": "Salwa.Khalaf@alef.ae",
    "Alef IT Support Team Lead": "Marwa Ahmed Ibrahim Ahmed Gheith",
    "Alef IT Support Team Lead Contact Number": 505207391,
    "Alef IT Support Team Lead Email": "marwa.gheith@alef.ae"
  },
  {
    "School ID": 941,
    "School Name": "Al Nokhba",
    "School Name Arabic": "النخبة",
    "Region": "Al Dhafra",
    "Address": "AL MARFA",
    "GPS_LATITUDE": 24.0799,
    "GPS_LONGITUDE": 53.4781,
    "Gender": "M",
    "Alef IT Support Specialist": "Ayman Mohammed Muzzamail Albashear",
    "Alef IT Support Specialist Contact Number": "0505179178",
    "Alef IT Support Specialist Email": "Ayman.Muzzamail@alef.ae",
    "Alef IT Support Team Lead": "Anas Mamoun Eid Kamar",
    "Alef IT Support Team Lead Contact Number": 509869405,
    "Alef IT Support Team Lead Email": "anas.mamoun@alef.ae"
  },
  {
    "School ID": 942,
    "School Name": "Al Shumookh",
    "School Name Arabic": "الشموخ",
    "Region": "Al Dhafra",
    "Address": "AL MARFA",
    "GPS_LATITUDE": 24.09092373,
    "GPS_LONGITUDE": 53.47146641,
    "Gender": "F",
    "Alef IT Support Specialist": "Mai Mustafa Ali",
    "Alef IT Support Specialist Contact Number": "0565486725",
    "Alef IT Support Specialist Email": "mai.ali@alef.ae",
    "Alef IT Support Team Lead": "Marwa Ahmed Ibrahim Ahmed Gheith",
    "Alef IT Support Team Lead Contact Number": 505207391,
    "Alef IT Support Team Lead Email": "marwa.gheith@alef.ae"
  },
  {
    "School ID": 1151,
    "School Name": "Bedaa Al Mutawa",
    "School Name Arabic": "بدع المطاوعة",
    "Region": "Al Dhafra",
    "Address": "BIDA AL MUTAWA",
    "GPS_LATITUDE": 23.7825,
    "GPS_LONGITUDE": 52.5761,
    "Gender": "0",
    "Alef IT Support Specialist": "Hiba Ahmed Mohmed Awad",
    "Alef IT Support Specialist Contact Number": "0569943589",
    "Alef IT Support Specialist Email": "Hiba.Awad@alef.ae",
    "Alef IT Support Team Lead": "Marwa Ahmed Ibrahim Ahmed Gheith",
    "Alef IT Support Team Lead Contact Number": 505207391,
    "Alef IT Support Team Lead Email": "marwa.gheith@alef.ae"
  },
  {
    "School ID": 1562,
    "School Name": "Al Huiteen",
    "School Name Arabic": "الحويتين",
    "Region": "Al Dhafra",
    "Address": "LIWA",
    "GPS_LATITUDE": 23.1193,
    "GPS_LONGITUDE": 53.9257,
    "Gender": "F",
    "Alef IT Support Specialist": "Noralhuda Ibrahim Seleman",
    "Alef IT Support Specialist Contact Number": "0566892877",
    "Alef IT Support Specialist Email": "Noralhuda.Seleman@alef.ae",
    "Alef IT Support Team Lead": "Marwa Ahmed Ibrahim Ahmed Gheith",
    "Alef IT Support Team Lead Contact Number": 505207391,
    "Alef IT Support Team Lead Email": "marwa.gheith@alef.ae"
  },
  {
    "School ID": 1563,
    "School Name": "Khanoor",
    "School Name Arabic": "خنور",
    "Region": "Al Dhafra",
    "Address": "LIWA",
    "GPS_LATITUDE": 23.0953,
    "GPS_LONGITUDE": 53.6073,
    "Gender": "F",
    "Alef IT Support Specialist": "Ahlam Kamel Amro",
    "Alef IT Support Specialist Contact Number": "0566892608",
    "Alef IT Support Specialist Email": "ahlam.amro@alef.ae",
    "Alef IT Support Team Lead": "Marwa Ahmed Ibrahim Ahmed Gheith",
    "Alef IT Support Team Lead Contact Number": 505207391,
    "Alef IT Support Team Lead Email": "marwa.gheith@alef.ae"
  },
  {
    "School ID": 1564,
    "School Name": "Al Shabhana",
    "School Name Arabic": "الشبهانة",
    "Region": "Al Dhafra",
    "Address": "BAYAH AL SILA",
    "GPS_LATITUDE": 24.06423181,
    "GPS_LONGITUDE": 51.76438566,
    "Gender": "M",
    "Alef IT Support Specialist": "Anas Omar Golam Khalifah",
    "Alef IT Support Specialist Contact Number": "0566893140",
    "Alef IT Support Specialist Email": "Anas.Khalifah@alef.ae",
    "Alef IT Support Team Lead": "Anas Mamoun Eid Kamar",
    "Alef IT Support Team Lead Contact Number": 509869405,
    "Alef IT Support Team Lead Email": "anas.mamoun@alef.ae"
  },
  {
    "School ID": 1565,
    "School Name": "Bayah",
    "School Name Arabic": "بعيا",
    "Region": "Al Dhafra",
    "Address": "BAYAH AL SILA",
    "GPS_LATITUDE": 24.07824753,
    "GPS_LONGITUDE": 51.76343313,
    "Gender": "F",
    "Alef IT Support Specialist": "Abeer Abdulmawla Al Hasan",
    "Alef IT Support Specialist Contact Number": "0569941520",
    "Alef IT Support Specialist Email": "abeer.hasan@alef.ae",
    "Alef IT Support Team Lead": "Marwa Ahmed Ibrahim Ahmed Gheith",
    "Alef IT Support Team Lead Contact Number": 505207391,
    "Alef IT Support Team Lead Email": "marwa.gheith@alef.ae"
  },
  {
    "School ID": 1643,
    "School Name": "Al Falah",
    "School Name Arabic": "الفلاح",
    "Region": "Al Dhafra",
    "Address": "MADINAT ZAYED",
    "GPS_LATITUDE": 23.66387006,
    "GPS_LONGITUDE": 53.70137642,
    "Gender": "M",
    "Alef IT Support Specialist": "ALMAMOUN MOHAMED MOHIELDIN KHALIL",
    "Alef IT Support Specialist Contact Number": "0505178341",
    "Alef IT Support Specialist Email": "Almamoun.Khalil@alef.ae",
    "Alef IT Support Team Lead": "Anas Mamoun Eid Kamar",
    "Alef IT Support Team Lead Contact Number": 509869405,
    "Alef IT Support Team Lead Email": "anas.mamoun@alef.ae"
  },
  {
    "School ID": 1662,
    "School Name": "Al Ebtekar",
    "School Name Arabic": "الإبتكار",
    "Region": "Al Dhafra",
    "Address": "GHAYATHI",
    "GPS_LATITUDE": 23.83029108,
    "GPS_LONGITUDE": 52.81130369,
    "Gender": "M",
    "Alef IT Support Specialist": "Yazeed Ibrahim Ahmed Mohammed",
    "Alef IT Support Specialist Contact Number": "0569943182",
    "Alef IT Support Specialist Email": "Yazeed.Mohammed@alef.ae",
    "Alef IT Support Team Lead": "Anas Mamoun Eid Kamar",
    "Alef IT Support Team Lead Contact Number": 509869405,
    "Alef IT Support Team Lead Email": "anas.mamoun@alef.ae"
  },
  {
    "School ID": 1682,
    "School Name": "Baynouna",
    "School Name Arabic": "بينونة",
    "Region": "Al Dhafra",
    "Address": "GHAYATHI",
    "GPS_LATITUDE": 23.85466428,
    "GPS_LONGITUDE": 52.80688274,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohamed Awad Abdalrahman Abdalla",
    "Alef IT Support Specialist Contact Number": "0505198226",
    "Alef IT Support Specialist Email": "mohamed.abdallah@alef.ae",
    "Alef IT Support Team Lead": "Anas Mamoun Eid Kamar",
    "Alef IT Support Team Lead Contact Number": 509869405,
    "Alef IT Support Team Lead Email": "anas.mamoun@alef.ae"
  },
  {
    "School ID": 1762,
    "School Name": "Amra Bint Abdel Rahman",
    "School Name Arabic": "عمرة بنت عبد الرحمن",
    "Region": "Al Dhafra",
    "Address": "AL RUWAIS",
    "GPS_LATITUDE": 24.0865,
    "GPS_LONGITUDE": 52.6487,
    "Gender": "F",
    "Alef IT Support Specialist": "Rawan Abduljawad Sobhi",
    "Alef IT Support Specialist Contact Number": "0566885894",
    "Alef IT Support Specialist Email": "rawan.sobhi@alef.ae",
    "Alef IT Support Team Lead": "Marwa Ahmed Ibrahim Ahmed Gheith",
    "Alef IT Support Team Lead Contact Number": 505207391,
    "Alef IT Support Team Lead Email": "marwa.gheith@alef.ae"
  },
  {
    "School ID": 2005,
    "School Name": "Al Dhafra",
    "School Name Arabic": " الظفرة",
    "Region": "Al Dhafra",
    "Address": "MADINAT ZAYED",
    "GPS_LATITUDE": 23.6645,
    "GPS_LONGITUDE": 53.7033,
    "Gender": "M",
    "Alef IT Support Specialist": "Abou hamed el ghazaly Atih",
    "Alef IT Support Specialist Contact Number": "0505175605",
    "Alef IT Support Specialist Email": "abouhamed.atih@alef.ae",
    "Alef IT Support Team Lead": "Anas Mamoun Eid Kamar",
    "Alef IT Support Team Lead Contact Number": 509869405,
    "Alef IT Support Team Lead Email": "anas.mamoun@alef.ae"
  },
  {
    "School ID": 2017,
    "School Name": "Dalma",
    "School Name Arabic": "دلما",
    "Region": "Al Dhafra",
    "Address": "DALMA ISLAND",
    "GPS_LATITUDE": 24.494653717,
    "GPS_LONGITUDE": 52.326305883,
    "Gender": "F",
    "Alef IT Support Specialist": "Rasha Alshana",
    "Alef IT Support Specialist Contact Number": "0566893409",
    "Alef IT Support Specialist Email": "Rasha.Alshana@alef.ae",
    "Alef IT Support Team Lead": "Marwa Ahmed Ibrahim Ahmed Gheith",
    "Alef IT Support Team Lead Contact Number": 505207391,
    "Alef IT Support Team Lead Email": "marwa.gheith@alef.ae"
  },
  {
    "School ID": 2025,
    "School Name": "Al Hosn Scinetific",
    "School Name Arabic": "الحصن العلمية",
    "Region": "Al Dhafra",
    "Address": "DALMA ISLAND",
    "GPS_LATITUDE": 24.4636,
    "GPS_LONGITUDE": 52.3142,
    "Gender": "M",
    "Alef IT Support Specialist": "Mohamed Mustafa Hamdan",
    "Alef IT Support Specialist Contact Number": "0566893156",
    "Alef IT Support Specialist Email": "Mohamed.Hamdan@alef.ae",
    "Alef IT Support Team Lead": "Anas Mamoun Eid Kamar",
    "Alef IT Support Team Lead Contact Number": 509869405,
    "Alef IT Support Team Lead Email": "anas.mamoun@alef.ae"
  },
  {
    "School ID": 8059,
    "School Name": "Al Fujairah",
    "School Name Arabic": "الفجيرة",
    "Region": "Fujairah",
    "Address": "Seif Dawlah Rd",
    "GPS_LATITUDE": 25.150833,
    "GPS_LONGITUDE": 56.347806,
    "Gender": "F",
    "Alef IT Support Specialist": "Omneya Gamal",
    "Alef IT Support Specialist Contact Number": "0564019041",
    "Alef IT Support Specialist Email": "omneya@alef.ae",
    "Alef IT Support Team Lead": "Samah Mukhtar",
    "Alef IT Support Team Lead Contact Number": 564008391,
    "Alef IT Support Team Lead Email": "samah.mukhtar@alef.ae"
  }
 ]